#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ANALYTICS")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEngagement_NetPromoterScore(Engagement_NetPromoterScore instance);
    partial void UpdateEngagement_NetPromoterScore(Engagement_NetPromoterScore instance);
    partial void DeleteEngagement_NetPromoterScore(Engagement_NetPromoterScore instance);
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ANALYTICSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Engagement_NetPromoterScore> Engagement_NetPromoterScores
		{
			get
			{
				return this.GetTable<Engagement_NetPromoterScore>();
			}
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Engagement_NetPromoterScore")]
	public partial class Engagement_NetPromoterScore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _CustomerId;
		
		private int _NPSEngagementId;
		
		private System.Nullable<System.DateTime> _NPSSendDate;
		
		private System.Nullable<System.DateTime> _NPSResultDate;
		
		private System.Nullable<int> _NPSScore;
		
		private string _EngagementType;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreateDateTime;
		
		private string _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdateDateTime;
		
		private string _NPSComments;
		
		private string _MasterCustomerId;
		
		private string _ReferenceId;
		
		private string _AlchemySentimentType;
		
		private System.Nullable<double> _AlchemySentimentScore;
		
		private string _PromoteDetract;
		
		private bool _SentToSlack;
		
		private EntityRef<Customer> _Customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIdChanging(System.Nullable<int> value);
    partial void OnCustomerIdChanged();
    partial void OnNPSEngagementIdChanging(int value);
    partial void OnNPSEngagementIdChanged();
    partial void OnNPSSendDateChanging(System.Nullable<System.DateTime> value);
    partial void OnNPSSendDateChanged();
    partial void OnNPSResultDateChanging(System.Nullable<System.DateTime> value);
    partial void OnNPSResultDateChanged();
    partial void OnNPSScoreChanging(System.Nullable<int> value);
    partial void OnNPSScoreChanged();
    partial void OnEngagementTypeChanging(string value);
    partial void OnEngagementTypeChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnCreateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateTimeChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateTimeChanged();
    partial void OnNPSCommentsChanging(string value);
    partial void OnNPSCommentsChanged();
    partial void OnMasterCustomerIdChanging(string value);
    partial void OnMasterCustomerIdChanged();
    partial void OnReferenceIdChanging(string value);
    partial void OnReferenceIdChanged();
    partial void OnAlchemySentimentTypeChanging(string value);
    partial void OnAlchemySentimentTypeChanged();
    partial void OnAlchemySentimentScoreChanging(System.Nullable<double> value);
    partial void OnAlchemySentimentScoreChanged();
    partial void OnPromoteDetractChanging(string value);
    partial void OnPromoteDetractChanged();
    partial void OnSentToSlackChanging(bool value);
    partial void OnSentToSlackChanged();
    #endregion
		
		public Engagement_NetPromoterScore()
		{
			this._Customer = default(EntityRef<Customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="Int")]
		public System.Nullable<int> CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					if (this._Customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPSEngagementId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NPSEngagementId
		{
			get
			{
				return this._NPSEngagementId;
			}
			set
			{
				if ((this._NPSEngagementId != value))
				{
					this.OnNPSEngagementIdChanging(value);
					this.SendPropertyChanging();
					this._NPSEngagementId = value;
					this.SendPropertyChanged("NPSEngagementId");
					this.OnNPSEngagementIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPSSendDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NPSSendDate
		{
			get
			{
				return this._NPSSendDate;
			}
			set
			{
				if ((this._NPSSendDate != value))
				{
					this.OnNPSSendDateChanging(value);
					this.SendPropertyChanging();
					this._NPSSendDate = value;
					this.SendPropertyChanged("NPSSendDate");
					this.OnNPSSendDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPSResultDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NPSResultDate
		{
			get
			{
				return this._NPSResultDate;
			}
			set
			{
				if ((this._NPSResultDate != value))
				{
					this.OnNPSResultDateChanging(value);
					this.SendPropertyChanging();
					this._NPSResultDate = value;
					this.SendPropertyChanged("NPSResultDate");
					this.OnNPSResultDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPSScore", DbType="Int")]
		public System.Nullable<int> NPSScore
		{
			get
			{
				return this._NPSScore;
			}
			set
			{
				if ((this._NPSScore != value))
				{
					this.OnNPSScoreChanging(value);
					this.SendPropertyChanging();
					this._NPSScore = value;
					this.SendPropertyChanged("NPSScore");
					this.OnNPSScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngagementType", DbType="VarChar(25)")]
		public string EngagementType
		{
			get
			{
				return this._EngagementType;
			}
			set
			{
				if ((this._EngagementType != value))
				{
					this.OnEngagementTypeChanging(value);
					this.SendPropertyChanging();
					this._EngagementType = value;
					this.SendPropertyChanged("EngagementType");
					this.OnEngagementTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDateTime
		{
			get
			{
				return this._CreateDateTime;
			}
			set
			{
				if ((this._CreateDateTime != value))
				{
					this.OnCreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateDateTime = value;
					this.SendPropertyChanged("CreateDateTime");
					this.OnCreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="VarChar(50)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDateTime
		{
			get
			{
				return this._UpdateDateTime;
			}
			set
			{
				if ((this._UpdateDateTime != value))
				{
					this.OnUpdateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateDateTime = value;
					this.SendPropertyChanged("UpdateDateTime");
					this.OnUpdateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPSComments", DbType="VarChar(MAX)")]
		public string NPSComments
		{
			get
			{
				return this._NPSComments;
			}
			set
			{
				if ((this._NPSComments != value))
				{
					this.OnNPSCommentsChanging(value);
					this.SendPropertyChanging();
					this._NPSComments = value;
					this.SendPropertyChanged("NPSComments");
					this.OnNPSCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterCustomerId", DbType="VarChar(10)")]
		public string MasterCustomerId
		{
			get
			{
				return this._MasterCustomerId;
			}
			set
			{
				if ((this._MasterCustomerId != value))
				{
					this.OnMasterCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._MasterCustomerId = value;
					this.SendPropertyChanged("MasterCustomerId");
					this.OnMasterCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceId", DbType="VarChar(255)")]
		public string ReferenceId
		{
			get
			{
				return this._ReferenceId;
			}
			set
			{
				if ((this._ReferenceId != value))
				{
					this.OnReferenceIdChanging(value);
					this.SendPropertyChanging();
					this._ReferenceId = value;
					this.SendPropertyChanged("ReferenceId");
					this.OnReferenceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlchemySentimentType", DbType="VarChar(20)")]
		public string AlchemySentimentType
		{
			get
			{
				return this._AlchemySentimentType;
			}
			set
			{
				if ((this._AlchemySentimentType != value))
				{
					this.OnAlchemySentimentTypeChanging(value);
					this.SendPropertyChanging();
					this._AlchemySentimentType = value;
					this.SendPropertyChanged("AlchemySentimentType");
					this.OnAlchemySentimentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlchemySentimentScore", DbType="Float")]
		public System.Nullable<double> AlchemySentimentScore
		{
			get
			{
				return this._AlchemySentimentScore;
			}
			set
			{
				if ((this._AlchemySentimentScore != value))
				{
					this.OnAlchemySentimentScoreChanging(value);
					this.SendPropertyChanging();
					this._AlchemySentimentScore = value;
					this.SendPropertyChanged("AlchemySentimentScore");
					this.OnAlchemySentimentScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromoteDetract", DbType="VarChar(25)")]
		public string PromoteDetract
		{
			get
			{
				return this._PromoteDetract;
			}
			set
			{
				if ((this._PromoteDetract != value))
				{
					this.OnPromoteDetractChanging(value);
					this.SendPropertyChanging();
					this._PromoteDetract = value;
					this.SendPropertyChanged("PromoteDetract");
					this.OnPromoteDetractChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SentToSlack", DbType="Bit NOT NULL")]
		public bool SentToSlack
		{
			get
			{
				return this._SentToSlack;
			}
			set
			{
				if ((this._SentToSlack != value))
				{
					this.OnSentToSlackChanging(value);
					this.SendPropertyChanging();
					this._SentToSlack = value;
					this.SendPropertyChanged("SentToSlack");
					this.OnSentToSlackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Engagement_NetPromoterScore", Storage="_Customer", ThisKey="CustomerId", OtherKey="CustomerId", IsForeignKey=true, DeleteRule="SET NULL")]
		public Customer Customer
		{
			get
			{
				return this._Customer.Entity;
			}
			set
			{
				Customer previousValue = this._Customer.Entity;
				if (((previousValue != value) 
							|| (this._Customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer.Entity = null;
						previousValue.Engagement_NetPromoterScores.Remove(this);
					}
					this._Customer.Entity = value;
					if ((value != null))
					{
						value.Engagement_NetPromoterScores.Add(this);
						this._CustomerId = value.CustomerId;
					}
					else
					{
						this._CustomerId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerId;
		
		private string _PrimaryEmailAddress;
		
		private string _MasterCustomerId;
		
		private System.Nullable<int> _ParatureCustomerId;
		
		private string _CustFirstName;
		
		private string _CustLastName;
		
		private string _CustCity;
		
		private string _CustState;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreateDateTime;
		
		private string _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdateDateTime;
		
		private string _CountryCode;
		
		private string _CustZip;
		
		private System.Nullable<System.DateTime> _WebventProfileCreated;
		
		private System.Nullable<System.DateTime> _PersonifyProfileDeactivated;
		
		private System.Nullable<System.DateTime> _PersonifyProfileCreated;
		
		private System.Nullable<int> _WebventPersonId;
		
		private System.Nullable<int> _dupalert;
		
		private string _StreetAddress;
		
		private System.Nullable<decimal> _CustLatitude;
		
		private System.Nullable<decimal> _CustLongitude;
		
		private string _ZendeskId;
		
		private string _AllowEmail;
		
		private System.Nullable<System.DateTime> _EmailOptOutDate;
		
		private string _AllowPhone;
		
		private string _AllowSolicitation;
		
		private string _NixieAddress;
		
		private EntitySet<Engagement_NetPromoterScore> _Engagement_NetPromoterScores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIdChanging(int value);
    partial void OnCustomerIdChanged();
    partial void OnPrimaryEmailAddressChanging(string value);
    partial void OnPrimaryEmailAddressChanged();
    partial void OnMasterCustomerIdChanging(string value);
    partial void OnMasterCustomerIdChanged();
    partial void OnParatureCustomerIdChanging(System.Nullable<int> value);
    partial void OnParatureCustomerIdChanged();
    partial void OnCustFirstNameChanging(string value);
    partial void OnCustFirstNameChanged();
    partial void OnCustLastNameChanging(string value);
    partial void OnCustLastNameChanged();
    partial void OnCustCityChanging(string value);
    partial void OnCustCityChanged();
    partial void OnCustStateChanging(string value);
    partial void OnCustStateChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnCreateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateTimeChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateTimeChanged();
    partial void OnCountryCodeChanging(string value);
    partial void OnCountryCodeChanged();
    partial void OnCustZipChanging(string value);
    partial void OnCustZipChanged();
    partial void OnWebventProfileCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnWebventProfileCreatedChanged();
    partial void OnPersonifyProfileDeactivatedChanging(System.Nullable<System.DateTime> value);
    partial void OnPersonifyProfileDeactivatedChanged();
    partial void OnPersonifyProfileCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnPersonifyProfileCreatedChanged();
    partial void OnWebventPersonIdChanging(System.Nullable<int> value);
    partial void OnWebventPersonIdChanged();
    partial void OndupalertChanging(System.Nullable<int> value);
    partial void OndupalertChanged();
    partial void OnStreetAddressChanging(string value);
    partial void OnStreetAddressChanged();
    partial void OnCustLatitudeChanging(System.Nullable<decimal> value);
    partial void OnCustLatitudeChanged();
    partial void OnCustLongitudeChanging(System.Nullable<decimal> value);
    partial void OnCustLongitudeChanged();
    partial void OnZendeskIdChanging(string value);
    partial void OnZendeskIdChanged();
    partial void OnAllowEmailChanging(string value);
    partial void OnAllowEmailChanged();
    partial void OnEmailOptOutDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEmailOptOutDateChanged();
    partial void OnAllowPhoneChanging(string value);
    partial void OnAllowPhoneChanged();
    partial void OnAllowSolicitationChanging(string value);
    partial void OnAllowSolicitationChanged();
    partial void OnNixieAddressChanging(string value);
    partial void OnNixieAddressChanged();
    #endregion
		
		public Customer()
		{
			this._Engagement_NetPromoterScores = new EntitySet<Engagement_NetPromoterScore>(new Action<Engagement_NetPromoterScore>(this.attach_Engagement_NetPromoterScores), new Action<Engagement_NetPromoterScore>(this.detach_Engagement_NetPromoterScores));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryEmailAddress", DbType="VarChar(256)")]
		public string PrimaryEmailAddress
		{
			get
			{
				return this._PrimaryEmailAddress;
			}
			set
			{
				if ((this._PrimaryEmailAddress != value))
				{
					this.OnPrimaryEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._PrimaryEmailAddress = value;
					this.SendPropertyChanged("PrimaryEmailAddress");
					this.OnPrimaryEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterCustomerId", DbType="VarChar(10)")]
		public string MasterCustomerId
		{
			get
			{
				return this._MasterCustomerId;
			}
			set
			{
				if ((this._MasterCustomerId != value))
				{
					this.OnMasterCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._MasterCustomerId = value;
					this.SendPropertyChanged("MasterCustomerId");
					this.OnMasterCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParatureCustomerId", DbType="Int")]
		public System.Nullable<int> ParatureCustomerId
		{
			get
			{
				return this._ParatureCustomerId;
			}
			set
			{
				if ((this._ParatureCustomerId != value))
				{
					this.OnParatureCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._ParatureCustomerId = value;
					this.SendPropertyChanged("ParatureCustomerId");
					this.OnParatureCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustFirstName", DbType="VarChar(128)")]
		public string CustFirstName
		{
			get
			{
				return this._CustFirstName;
			}
			set
			{
				if ((this._CustFirstName != value))
				{
					this.OnCustFirstNameChanging(value);
					this.SendPropertyChanging();
					this._CustFirstName = value;
					this.SendPropertyChanged("CustFirstName");
					this.OnCustFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustLastName", DbType="VarChar(128)")]
		public string CustLastName
		{
			get
			{
				return this._CustLastName;
			}
			set
			{
				if ((this._CustLastName != value))
				{
					this.OnCustLastNameChanging(value);
					this.SendPropertyChanging();
					this._CustLastName = value;
					this.SendPropertyChanged("CustLastName");
					this.OnCustLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustCity", DbType="VarChar(100)")]
		public string CustCity
		{
			get
			{
				return this._CustCity;
			}
			set
			{
				if ((this._CustCity != value))
				{
					this.OnCustCityChanging(value);
					this.SendPropertyChanging();
					this._CustCity = value;
					this.SendPropertyChanged("CustCity");
					this.OnCustCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustState", DbType="VarChar(100)")]
		public string CustState
		{
			get
			{
				return this._CustState;
			}
			set
			{
				if ((this._CustState != value))
				{
					this.OnCustStateChanging(value);
					this.SendPropertyChanging();
					this._CustState = value;
					this.SendPropertyChanged("CustState");
					this.OnCustStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDateTime
		{
			get
			{
				return this._CreateDateTime;
			}
			set
			{
				if ((this._CreateDateTime != value))
				{
					this.OnCreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateDateTime = value;
					this.SendPropertyChanged("CreateDateTime");
					this.OnCreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="VarChar(50)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDateTime
		{
			get
			{
				return this._UpdateDateTime;
			}
			set
			{
				if ((this._UpdateDateTime != value))
				{
					this.OnUpdateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateDateTime = value;
					this.SendPropertyChanged("UpdateDateTime");
					this.OnUpdateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryCode", DbType="VarChar(3)")]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this.OnCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._CountryCode = value;
					this.SendPropertyChanged("CountryCode");
					this.OnCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustZip", DbType="VarChar(20)")]
		public string CustZip
		{
			get
			{
				return this._CustZip;
			}
			set
			{
				if ((this._CustZip != value))
				{
					this.OnCustZipChanging(value);
					this.SendPropertyChanging();
					this._CustZip = value;
					this.SendPropertyChanged("CustZip");
					this.OnCustZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebventProfileCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> WebventProfileCreated
		{
			get
			{
				return this._WebventProfileCreated;
			}
			set
			{
				if ((this._WebventProfileCreated != value))
				{
					this.OnWebventProfileCreatedChanging(value);
					this.SendPropertyChanging();
					this._WebventProfileCreated = value;
					this.SendPropertyChanged("WebventProfileCreated");
					this.OnWebventProfileCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonifyProfileDeactivated", DbType="DateTime")]
		public System.Nullable<System.DateTime> PersonifyProfileDeactivated
		{
			get
			{
				return this._PersonifyProfileDeactivated;
			}
			set
			{
				if ((this._PersonifyProfileDeactivated != value))
				{
					this.OnPersonifyProfileDeactivatedChanging(value);
					this.SendPropertyChanging();
					this._PersonifyProfileDeactivated = value;
					this.SendPropertyChanged("PersonifyProfileDeactivated");
					this.OnPersonifyProfileDeactivatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonifyProfileCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> PersonifyProfileCreated
		{
			get
			{
				return this._PersonifyProfileCreated;
			}
			set
			{
				if ((this._PersonifyProfileCreated != value))
				{
					this.OnPersonifyProfileCreatedChanging(value);
					this.SendPropertyChanging();
					this._PersonifyProfileCreated = value;
					this.SendPropertyChanged("PersonifyProfileCreated");
					this.OnPersonifyProfileCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebventPersonId", DbType="Int")]
		public System.Nullable<int> WebventPersonId
		{
			get
			{
				return this._WebventPersonId;
			}
			set
			{
				if ((this._WebventPersonId != value))
				{
					this.OnWebventPersonIdChanging(value);
					this.SendPropertyChanging();
					this._WebventPersonId = value;
					this.SendPropertyChanged("WebventPersonId");
					this.OnWebventPersonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dupalert", DbType="Int")]
		public System.Nullable<int> dupalert
		{
			get
			{
				return this._dupalert;
			}
			set
			{
				if ((this._dupalert != value))
				{
					this.OndupalertChanging(value);
					this.SendPropertyChanging();
					this._dupalert = value;
					this.SendPropertyChanged("dupalert");
					this.OndupalertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetAddress", DbType="VarChar(250)")]
		public string StreetAddress
		{
			get
			{
				return this._StreetAddress;
			}
			set
			{
				if ((this._StreetAddress != value))
				{
					this.OnStreetAddressChanging(value);
					this.SendPropertyChanging();
					this._StreetAddress = value;
					this.SendPropertyChanged("StreetAddress");
					this.OnStreetAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustLatitude", DbType="Decimal(8,5)")]
		public System.Nullable<decimal> CustLatitude
		{
			get
			{
				return this._CustLatitude;
			}
			set
			{
				if ((this._CustLatitude != value))
				{
					this.OnCustLatitudeChanging(value);
					this.SendPropertyChanging();
					this._CustLatitude = value;
					this.SendPropertyChanged("CustLatitude");
					this.OnCustLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustLongitude", DbType="Decimal(8,5)")]
		public System.Nullable<decimal> CustLongitude
		{
			get
			{
				return this._CustLongitude;
			}
			set
			{
				if ((this._CustLongitude != value))
				{
					this.OnCustLongitudeChanging(value);
					this.SendPropertyChanging();
					this._CustLongitude = value;
					this.SendPropertyChanged("CustLongitude");
					this.OnCustLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZendeskId", DbType="VarChar(20)")]
		public string ZendeskId
		{
			get
			{
				return this._ZendeskId;
			}
			set
			{
				if ((this._ZendeskId != value))
				{
					this.OnZendeskIdChanging(value);
					this.SendPropertyChanging();
					this._ZendeskId = value;
					this.SendPropertyChanged("ZendeskId");
					this.OnZendeskIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowEmail", DbType="VarChar(1)")]
		public string AllowEmail
		{
			get
			{
				return this._AllowEmail;
			}
			set
			{
				if ((this._AllowEmail != value))
				{
					this.OnAllowEmailChanging(value);
					this.SendPropertyChanging();
					this._AllowEmail = value;
					this.SendPropertyChanged("AllowEmail");
					this.OnAllowEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailOptOutDate", DbType="Date")]
		public System.Nullable<System.DateTime> EmailOptOutDate
		{
			get
			{
				return this._EmailOptOutDate;
			}
			set
			{
				if ((this._EmailOptOutDate != value))
				{
					this.OnEmailOptOutDateChanging(value);
					this.SendPropertyChanging();
					this._EmailOptOutDate = value;
					this.SendPropertyChanged("EmailOptOutDate");
					this.OnEmailOptOutDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowPhone", DbType="VarChar(1)")]
		public string AllowPhone
		{
			get
			{
				return this._AllowPhone;
			}
			set
			{
				if ((this._AllowPhone != value))
				{
					this.OnAllowPhoneChanging(value);
					this.SendPropertyChanging();
					this._AllowPhone = value;
					this.SendPropertyChanged("AllowPhone");
					this.OnAllowPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowSolicitation", DbType="VarChar(1)")]
		public string AllowSolicitation
		{
			get
			{
				return this._AllowSolicitation;
			}
			set
			{
				if ((this._AllowSolicitation != value))
				{
					this.OnAllowSolicitationChanging(value);
					this.SendPropertyChanging();
					this._AllowSolicitation = value;
					this.SendPropertyChanged("AllowSolicitation");
					this.OnAllowSolicitationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NixieAddress", DbType="VarChar(1)")]
		public string NixieAddress
		{
			get
			{
				return this._NixieAddress;
			}
			set
			{
				if ((this._NixieAddress != value))
				{
					this.OnNixieAddressChanging(value);
					this.SendPropertyChanging();
					this._NixieAddress = value;
					this.SendPropertyChanged("NixieAddress");
					this.OnNixieAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Engagement_NetPromoterScore", Storage="_Engagement_NetPromoterScores", ThisKey="CustomerId", OtherKey="CustomerId")]
		public EntitySet<Engagement_NetPromoterScore> Engagement_NetPromoterScores
		{
			get
			{
				return this._Engagement_NetPromoterScores;
			}
			set
			{
				this._Engagement_NetPromoterScores.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Engagement_NetPromoterScores(Engagement_NetPromoterScore entity)
		{
			this.SendPropertyChanging();
			entity.Customer = this;
		}
		
		private void detach_Engagement_NetPromoterScores(Engagement_NetPromoterScore entity)
		{
			this.SendPropertyChanging();
			entity.Customer = null;
		}
	}
}
#pragma warning restore 1591
