#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PROD")]
	public partial class NpsCustomerRepositoryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCUSTOMER(CUSTOMER instance);
    partial void UpdateCUSTOMER(CUSTOMER instance);
    partial void DeleteCUSTOMER(CUSTOMER instance);
    #endregion
		
		public NpsCustomerRepositoryDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NpsCustomerRepository"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NpsCustomerRepositoryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NpsCustomerRepositoryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NpsCustomerRepositoryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NpsCustomerRepositoryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CUSTOMER> CUSTOMERs
		{
			get
			{
				return this.GetTable<CUSTOMER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER")]
	public partial class CUSTOMER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASTER_CUSTOMER_ID;
		
		private decimal _SUB_CUSTOMER_ID;
		
		private string _ORG_ID;
		
		private string _ORG_UNIT_ID;
		
		private char _RECORD_TYPE;
		
		private string _SEARCH_NAME;
		
		private string _LABEL_NAME;
		
		private char _CAN_PLACE_ORDER_FLAG;
		
		private char _BILL_PRIMARY_ACCOUNT_FLAG;
		
		private string _NAME_PREFIX;
		
		private string _FIRST_NAME;
		
		private string _MIDDLE_NAME;
		
		private string _LAST_NAME;
		
		private string _NAME_SUFFIX;
		
		private string _NAME_CREDENTIALS;
		
		private string _NICKNAME;
		
		private string _FORMAL_SALUTATION;
		
		private string _INFORMAL_SALUTATION;
		
		private string _CUSTOMER_CLASS_CODE;
		
		private string _CUSTOMER_STATUS_CODE;
		
		private System.Nullable<System.DateTime> _CUSTOMER_STATUS_DATE;
		
		private char _ALLOW_FAX_FLAG;
		
		private char _ALLOW_EMAIL_FLAG;
		
		private char _ALLOW_PHONE_FLAG;
		
		private char _ALLOW_LABEL_SALES_FLAG;
		
		private char _ALLOW_SOLICITATION_FLAG;
		
		private char _ALLOW_INTERNAL_MAIL_FLAG;
		
		private System.Nullable<System.DateTime> _SOLICITATION_REMOVAL_DATE;
		
		private char _TAXABLE_FLAG;
		
		private string _FEDERAL_TAX_ID;
		
		private string _VAT_ID;
		
		private string _TAX_EXEMPT_ID;
		
		private string _SSN;
		
		private string _GENDER_CODE;
		
		private System.Nullable<System.DateTime> _BIRTH_DATE;
		
		private string _ETHNICITY_CODE;
		
		private string _ANNUAL_INCOME_RANGE_CODE;
		
		private string _JOB_FUNCTION_CODE;
		
		private string _REVENUE_RANGE_CODE;
		
		private string _STAFF_RANGE_CODE;
		
		private System.Nullable<char> _FOUNDATION_FLAG;
		
		private System.Nullable<char> _FND_MATCHING_FLAG;
		
		private System.Nullable<decimal> _FND_MATCHING_PERCENT;
		
		private System.Nullable<decimal> _FND_MATCHING_LIMIT;
		
		private string _LIST_CODE;
		
		private char _ENFORCE_COM_STRUCT_FLAG;
		
		private char _NOT_A_DUPLICATE_FLAG;
		
		private string _MERGED_TO_MAST_CUST;
		
		private System.Nullable<decimal> _MERGED_TO_SUB_CUST;
		
		private char _EXHIBITOR_FLAG;
		
		private System.Nullable<decimal> _VIP_COMMITTEE_PRIORITY;
		
		private string _HOME_PHONE;
		
		private string _WORK_PHONE;
		
		private string _PRIMARY_PHONE;
		
		private string _PRIMARY_FAX;
		
		private string _PRIMARY_EMAIL_ADDRESS;
		
		private string _PRIMARY_URL;
		
		private string _PRIMARY_JOB_TITLE;
		
		private string _PRIMARY_PHONE_LOCATION_CODE;
		
		private string _PRIMARY_EMAIL_LOCATION_CODE;
		
		private string _PRIMARY_FAX_LOCATION_CODE;
		
		private System.Nullable<char> _PUBLISH_PRIMARY_FAX_FLAG;
		
		private System.Nullable<char> _PUBLISH_PRIMARY_PHONE_FLAG;
		
		private System.Nullable<char> _PUBLISH_PRIMARY_EMAIL_FLAG;
		
		private System.Nullable<char> _PUBLISH_HOME_PHONE_FLAG;
		
		private System.Nullable<char> _PUBLISH_WORK_PHONE_FLAG;
		
		private string _DEFAULT_LANGUAGE_CODE;
		
		private string _ADDOPER;
		
		private System.DateTime _ADDDATE;
		
		private string _MODOPER;
		
		private System.Nullable<System.DateTime> _MODDATE;
		
		private decimal _CONCURRENCY_ID;
		
		private System.Nullable<decimal> _IMAGE_ID;
		
		private string _PREFERRED_COMM_METHOD_CODE;
		
		private System.Nullable<char> _BILL_PRIMARY_EMPLOYER_FLAG;
		
		private string _LAST_FIRST_NAME;
		
		private string _TRN_COUNTRY_CODE;
		
		private string _TRN_STATE_CODE;
		
		private System.Nullable<decimal> _ORIG_CUS_ADDRESS_ID;
		
		private string _ORIG_CUS_ADDRESS_TYPE_CODE;
		
		private char _WEB_SEGMENT_CREATION_FLAG;
		
		private string _SEGMENT_RULE_CODE;
		
		private string _SEGMENT_QUALIFIER1;
		
		private string _SEGMENT_QUALIFIER2;
		
		private System.Nullable<char> _INCLUDE_IN_DIRECTORY_FLAG;
		
		private string _SEGMENT_DESCR;
		
		private char _CAN_CREATE_SEGMENTS_FLAG;
		
		private string _USR_VENDOR_NO;
		
		private string _USR_JOB_TITLE_CODE;
		
		private string _USR_INDUSTRY_CODE;
		
		private string _USR_SIC_CODE;
		
		private string _USR_JOB_FUNCTION_CODE;
		
		private string _USR_COMPANY_SIZE_CODE;
		
		private char _USR_MEMBER_DIRECTORY;
		
		private System.Nullable<int> _MAILING_PER_YEAR;
		
		private string _PRIMARY_CONTACT_MAST_CUST_ID;
		
		private System.Nullable<decimal> _PRIMARY_CONTACT_SUB_CUST_ID;
		
		private string _SHORT_NAME_CODE;
		
		private char _OFFICIAL_COMMITTEE_FLAG;
		
		private string _COM_SUBGROUP_MAST_CUST_ID;
		
		private System.Nullable<decimal> _COM_SUBGROUP_SUB_CUST_ID;
		
		private System.Nullable<char> _CUS_VOLUNTEER_FLAG;
		
		private char _ADVERTISER_FLAG;
		
		private char _ADVERTISING_AGENCY_FLAG;
		
		private char _BPA_TITLE_ONLY_FLAG;
		
		private string _PROSPECT_ID;
		
		private char _POTENTIAL_DUPLICATE_REVIEW_FLAG;
		
		private string _DUPLICATE_REASON;
		
		private System.Nullable<decimal> _POTENTIAL_MATCH_PROBABILITY;
		
		private string _ORIGINAL_ORG_ID;
		
		private string _ORIGINAL_ORG_UNIT_ID;
		
		private string _ORIGINAL_SOURCE_CODE;
		
		private char _ALLOW_SYSTEM_NOTIFICATION_FLAG;
		
		private string _SPOUSE_FIRST_NAME;
		
		private string _MARITAL_STATUS_CODE;
		
		private System.Nullable<char> _ALLOW_ADVOCACY_FLAG;
		
		private string _CURRENCY_CODE;
		
		private string _PRIMARY_SEARCH_GROUP;
		
		private string _USR_CANDIDATE_ID_OVERRIDE;
		
		private System.Nullable<char> _USR_ALLOW_MARKETING_EMAIL;
		
		private System.Nullable<char> _USR_HEAP_MASTER;
		
		private System.Nullable<System.DateTime> _USR_GRADUATION_DATE;
		
		private string _USR_FACEBOOK_UID;
		
		private string _USR_AVATAR;
		
		private System.Nullable<char> _USR_FORUM_MEMBER;
		
		private System.Nullable<char> _USR_CUSTOMER_INFO_INCOMPLETE;
		
		private System.Nullable<char> _USR_FREE_MEMBERSHIP_UPGRADE;
		
		private char _FAMILY_FLAG;
		
		private System.Nullable<char> _PRIMARY_SEARCH_GROUP_OVERRIDE_FLAG;
		
		private string _NAME_CREDENTIALS_DESC;
		
		private string _PRIMARY_FAMILY_CONTACT_MAST_CUST_ID;
		
		private System.Nullable<decimal> _PRIMARY_FAMILY_CONTACT_SUB_CUST_ID;
		
		private char _INCLUDE_IN_WEB_MOBILE_DIRECTORY_FLAG;
		
		private char _GUEST_CHECKOUT_FLAG;
		
		private string _USR_TRAINING_BUDGET_SIZE_CODE;
		
		private string _USR_DIRECT_REPORT_COUNT_CODE;
		
		private string _USR_SSO_USERNAME;
		
		private string _USR_JOB_BANK_CODE;
		
		private string _USR_FORUM_MEMBER_SINCE;
		
		private string _USR_FORUM_PARTNER_CODE;
		
		private System.Nullable<System.DateTime> _USR_SELECTED_TERMSCONDITIONS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASTER_CUSTOMER_IDChanging(string value);
    partial void OnMASTER_CUSTOMER_IDChanged();
    partial void OnSUB_CUSTOMER_IDChanging(decimal value);
    partial void OnSUB_CUSTOMER_IDChanged();
    partial void OnORG_IDChanging(string value);
    partial void OnORG_IDChanged();
    partial void OnORG_UNIT_IDChanging(string value);
    partial void OnORG_UNIT_IDChanged();
    partial void OnRECORD_TYPEChanging(char value);
    partial void OnRECORD_TYPEChanged();
    partial void OnSEARCH_NAMEChanging(string value);
    partial void OnSEARCH_NAMEChanged();
    partial void OnLABEL_NAMEChanging(string value);
    partial void OnLABEL_NAMEChanged();
    partial void OnCAN_PLACE_ORDER_FLAGChanging(char value);
    partial void OnCAN_PLACE_ORDER_FLAGChanged();
    partial void OnBILL_PRIMARY_ACCOUNT_FLAGChanging(char value);
    partial void OnBILL_PRIMARY_ACCOUNT_FLAGChanged();
    partial void OnNAME_PREFIXChanging(string value);
    partial void OnNAME_PREFIXChanged();
    partial void OnFIRST_NAMEChanging(string value);
    partial void OnFIRST_NAMEChanged();
    partial void OnMIDDLE_NAMEChanging(string value);
    partial void OnMIDDLE_NAMEChanged();
    partial void OnLAST_NAMEChanging(string value);
    partial void OnLAST_NAMEChanged();
    partial void OnNAME_SUFFIXChanging(string value);
    partial void OnNAME_SUFFIXChanged();
    partial void OnNAME_CREDENTIALSChanging(string value);
    partial void OnNAME_CREDENTIALSChanged();
    partial void OnNICKNAMEChanging(string value);
    partial void OnNICKNAMEChanged();
    partial void OnFORMAL_SALUTATIONChanging(string value);
    partial void OnFORMAL_SALUTATIONChanged();
    partial void OnINFORMAL_SALUTATIONChanging(string value);
    partial void OnINFORMAL_SALUTATIONChanged();
    partial void OnCUSTOMER_CLASS_CODEChanging(string value);
    partial void OnCUSTOMER_CLASS_CODEChanged();
    partial void OnCUSTOMER_STATUS_CODEChanging(string value);
    partial void OnCUSTOMER_STATUS_CODEChanged();
    partial void OnCUSTOMER_STATUS_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCUSTOMER_STATUS_DATEChanged();
    partial void OnALLOW_FAX_FLAGChanging(char value);
    partial void OnALLOW_FAX_FLAGChanged();
    partial void OnALLOW_EMAIL_FLAGChanging(char value);
    partial void OnALLOW_EMAIL_FLAGChanged();
    partial void OnALLOW_PHONE_FLAGChanging(char value);
    partial void OnALLOW_PHONE_FLAGChanged();
    partial void OnALLOW_LABEL_SALES_FLAGChanging(char value);
    partial void OnALLOW_LABEL_SALES_FLAGChanged();
    partial void OnALLOW_SOLICITATION_FLAGChanging(char value);
    partial void OnALLOW_SOLICITATION_FLAGChanged();
    partial void OnALLOW_INTERNAL_MAIL_FLAGChanging(char value);
    partial void OnALLOW_INTERNAL_MAIL_FLAGChanged();
    partial void OnSOLICITATION_REMOVAL_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSOLICITATION_REMOVAL_DATEChanged();
    partial void OnTAXABLE_FLAGChanging(char value);
    partial void OnTAXABLE_FLAGChanged();
    partial void OnFEDERAL_TAX_IDChanging(string value);
    partial void OnFEDERAL_TAX_IDChanged();
    partial void OnVAT_IDChanging(string value);
    partial void OnVAT_IDChanged();
    partial void OnTAX_EXEMPT_IDChanging(string value);
    partial void OnTAX_EXEMPT_IDChanged();
    partial void OnSSNChanging(string value);
    partial void OnSSNChanged();
    partial void OnGENDER_CODEChanging(string value);
    partial void OnGENDER_CODEChanged();
    partial void OnBIRTH_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBIRTH_DATEChanged();
    partial void OnETHNICITY_CODEChanging(string value);
    partial void OnETHNICITY_CODEChanged();
    partial void OnANNUAL_INCOME_RANGE_CODEChanging(string value);
    partial void OnANNUAL_INCOME_RANGE_CODEChanged();
    partial void OnJOB_FUNCTION_CODEChanging(string value);
    partial void OnJOB_FUNCTION_CODEChanged();
    partial void OnREVENUE_RANGE_CODEChanging(string value);
    partial void OnREVENUE_RANGE_CODEChanged();
    partial void OnSTAFF_RANGE_CODEChanging(string value);
    partial void OnSTAFF_RANGE_CODEChanged();
    partial void OnFOUNDATION_FLAGChanging(System.Nullable<char> value);
    partial void OnFOUNDATION_FLAGChanged();
    partial void OnFND_MATCHING_FLAGChanging(System.Nullable<char> value);
    partial void OnFND_MATCHING_FLAGChanged();
    partial void OnFND_MATCHING_PERCENTChanging(System.Nullable<decimal> value);
    partial void OnFND_MATCHING_PERCENTChanged();
    partial void OnFND_MATCHING_LIMITChanging(System.Nullable<decimal> value);
    partial void OnFND_MATCHING_LIMITChanged();
    partial void OnLIST_CODEChanging(string value);
    partial void OnLIST_CODEChanged();
    partial void OnENFORCE_COM_STRUCT_FLAGChanging(char value);
    partial void OnENFORCE_COM_STRUCT_FLAGChanged();
    partial void OnNOT_A_DUPLICATE_FLAGChanging(char value);
    partial void OnNOT_A_DUPLICATE_FLAGChanged();
    partial void OnMERGED_TO_MAST_CUSTChanging(string value);
    partial void OnMERGED_TO_MAST_CUSTChanged();
    partial void OnMERGED_TO_SUB_CUSTChanging(System.Nullable<decimal> value);
    partial void OnMERGED_TO_SUB_CUSTChanged();
    partial void OnEXHIBITOR_FLAGChanging(char value);
    partial void OnEXHIBITOR_FLAGChanged();
    partial void OnVIP_COMMITTEE_PRIORITYChanging(System.Nullable<decimal> value);
    partial void OnVIP_COMMITTEE_PRIORITYChanged();
    partial void OnHOME_PHONEChanging(string value);
    partial void OnHOME_PHONEChanged();
    partial void OnWORK_PHONEChanging(string value);
    partial void OnWORK_PHONEChanged();
    partial void OnPRIMARY_PHONEChanging(string value);
    partial void OnPRIMARY_PHONEChanged();
    partial void OnPRIMARY_FAXChanging(string value);
    partial void OnPRIMARY_FAXChanged();
    partial void OnPRIMARY_EMAIL_ADDRESSChanging(string value);
    partial void OnPRIMARY_EMAIL_ADDRESSChanged();
    partial void OnPRIMARY_URLChanging(string value);
    partial void OnPRIMARY_URLChanged();
    partial void OnPRIMARY_JOB_TITLEChanging(string value);
    partial void OnPRIMARY_JOB_TITLEChanged();
    partial void OnPRIMARY_PHONE_LOCATION_CODEChanging(string value);
    partial void OnPRIMARY_PHONE_LOCATION_CODEChanged();
    partial void OnPRIMARY_EMAIL_LOCATION_CODEChanging(string value);
    partial void OnPRIMARY_EMAIL_LOCATION_CODEChanged();
    partial void OnPRIMARY_FAX_LOCATION_CODEChanging(string value);
    partial void OnPRIMARY_FAX_LOCATION_CODEChanged();
    partial void OnPUBLISH_PRIMARY_FAX_FLAGChanging(System.Nullable<char> value);
    partial void OnPUBLISH_PRIMARY_FAX_FLAGChanged();
    partial void OnPUBLISH_PRIMARY_PHONE_FLAGChanging(System.Nullable<char> value);
    partial void OnPUBLISH_PRIMARY_PHONE_FLAGChanged();
    partial void OnPUBLISH_PRIMARY_EMAIL_FLAGChanging(System.Nullable<char> value);
    partial void OnPUBLISH_PRIMARY_EMAIL_FLAGChanged();
    partial void OnPUBLISH_HOME_PHONE_FLAGChanging(System.Nullable<char> value);
    partial void OnPUBLISH_HOME_PHONE_FLAGChanged();
    partial void OnPUBLISH_WORK_PHONE_FLAGChanging(System.Nullable<char> value);
    partial void OnPUBLISH_WORK_PHONE_FLAGChanged();
    partial void OnDEFAULT_LANGUAGE_CODEChanging(string value);
    partial void OnDEFAULT_LANGUAGE_CODEChanged();
    partial void OnADDOPERChanging(string value);
    partial void OnADDOPERChanged();
    partial void OnADDDATEChanging(System.DateTime value);
    partial void OnADDDATEChanged();
    partial void OnMODOPERChanging(string value);
    partial void OnMODOPERChanged();
    partial void OnMODDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODDATEChanged();
    partial void OnCONCURRENCY_IDChanging(decimal value);
    partial void OnCONCURRENCY_IDChanged();
    partial void OnIMAGE_IDChanging(System.Nullable<decimal> value);
    partial void OnIMAGE_IDChanged();
    partial void OnPREFERRED_COMM_METHOD_CODEChanging(string value);
    partial void OnPREFERRED_COMM_METHOD_CODEChanged();
    partial void OnBILL_PRIMARY_EMPLOYER_FLAGChanging(System.Nullable<char> value);
    partial void OnBILL_PRIMARY_EMPLOYER_FLAGChanged();
    partial void OnLAST_FIRST_NAMEChanging(string value);
    partial void OnLAST_FIRST_NAMEChanged();
    partial void OnTRN_COUNTRY_CODEChanging(string value);
    partial void OnTRN_COUNTRY_CODEChanged();
    partial void OnTRN_STATE_CODEChanging(string value);
    partial void OnTRN_STATE_CODEChanged();
    partial void OnORIG_CUS_ADDRESS_IDChanging(System.Nullable<decimal> value);
    partial void OnORIG_CUS_ADDRESS_IDChanged();
    partial void OnORIG_CUS_ADDRESS_TYPE_CODEChanging(string value);
    partial void OnORIG_CUS_ADDRESS_TYPE_CODEChanged();
    partial void OnWEB_SEGMENT_CREATION_FLAGChanging(char value);
    partial void OnWEB_SEGMENT_CREATION_FLAGChanged();
    partial void OnSEGMENT_RULE_CODEChanging(string value);
    partial void OnSEGMENT_RULE_CODEChanged();
    partial void OnSEGMENT_QUALIFIER1Changing(string value);
    partial void OnSEGMENT_QUALIFIER1Changed();
    partial void OnSEGMENT_QUALIFIER2Changing(string value);
    partial void OnSEGMENT_QUALIFIER2Changed();
    partial void OnINCLUDE_IN_DIRECTORY_FLAGChanging(System.Nullable<char> value);
    partial void OnINCLUDE_IN_DIRECTORY_FLAGChanged();
    partial void OnSEGMENT_DESCRChanging(string value);
    partial void OnSEGMENT_DESCRChanged();
    partial void OnCAN_CREATE_SEGMENTS_FLAGChanging(char value);
    partial void OnCAN_CREATE_SEGMENTS_FLAGChanged();
    partial void OnUSR_VENDOR_NOChanging(string value);
    partial void OnUSR_VENDOR_NOChanged();
    partial void OnUSR_JOB_TITLE_CODEChanging(string value);
    partial void OnUSR_JOB_TITLE_CODEChanged();
    partial void OnUSR_INDUSTRY_CODEChanging(string value);
    partial void OnUSR_INDUSTRY_CODEChanged();
    partial void OnUSR_SIC_CODEChanging(string value);
    partial void OnUSR_SIC_CODEChanged();
    partial void OnUSR_JOB_FUNCTION_CODEChanging(string value);
    partial void OnUSR_JOB_FUNCTION_CODEChanged();
    partial void OnUSR_COMPANY_SIZE_CODEChanging(string value);
    partial void OnUSR_COMPANY_SIZE_CODEChanged();
    partial void OnUSR_MEMBER_DIRECTORYChanging(char value);
    partial void OnUSR_MEMBER_DIRECTORYChanged();
    partial void OnMAILING_PER_YEARChanging(System.Nullable<int> value);
    partial void OnMAILING_PER_YEARChanged();
    partial void OnPRIMARY_CONTACT_MAST_CUST_IDChanging(string value);
    partial void OnPRIMARY_CONTACT_MAST_CUST_IDChanged();
    partial void OnPRIMARY_CONTACT_SUB_CUST_IDChanging(System.Nullable<decimal> value);
    partial void OnPRIMARY_CONTACT_SUB_CUST_IDChanged();
    partial void OnSHORT_NAME_CODEChanging(string value);
    partial void OnSHORT_NAME_CODEChanged();
    partial void OnOFFICIAL_COMMITTEE_FLAGChanging(char value);
    partial void OnOFFICIAL_COMMITTEE_FLAGChanged();
    partial void OnCOM_SUBGROUP_MAST_CUST_IDChanging(string value);
    partial void OnCOM_SUBGROUP_MAST_CUST_IDChanged();
    partial void OnCOM_SUBGROUP_SUB_CUST_IDChanging(System.Nullable<decimal> value);
    partial void OnCOM_SUBGROUP_SUB_CUST_IDChanged();
    partial void OnCUS_VOLUNTEER_FLAGChanging(System.Nullable<char> value);
    partial void OnCUS_VOLUNTEER_FLAGChanged();
    partial void OnADVERTISER_FLAGChanging(char value);
    partial void OnADVERTISER_FLAGChanged();
    partial void OnADVERTISING_AGENCY_FLAGChanging(char value);
    partial void OnADVERTISING_AGENCY_FLAGChanged();
    partial void OnBPA_TITLE_ONLY_FLAGChanging(char value);
    partial void OnBPA_TITLE_ONLY_FLAGChanged();
    partial void OnPROSPECT_IDChanging(string value);
    partial void OnPROSPECT_IDChanged();
    partial void OnPOTENTIAL_DUPLICATE_REVIEW_FLAGChanging(char value);
    partial void OnPOTENTIAL_DUPLICATE_REVIEW_FLAGChanged();
    partial void OnDUPLICATE_REASONChanging(string value);
    partial void OnDUPLICATE_REASONChanged();
    partial void OnPOTENTIAL_MATCH_PROBABILITYChanging(System.Nullable<decimal> value);
    partial void OnPOTENTIAL_MATCH_PROBABILITYChanged();
    partial void OnORIGINAL_ORG_IDChanging(string value);
    partial void OnORIGINAL_ORG_IDChanged();
    partial void OnORIGINAL_ORG_UNIT_IDChanging(string value);
    partial void OnORIGINAL_ORG_UNIT_IDChanged();
    partial void OnORIGINAL_SOURCE_CODEChanging(string value);
    partial void OnORIGINAL_SOURCE_CODEChanged();
    partial void OnALLOW_SYSTEM_NOTIFICATION_FLAGChanging(char value);
    partial void OnALLOW_SYSTEM_NOTIFICATION_FLAGChanged();
    partial void OnSPOUSE_FIRST_NAMEChanging(string value);
    partial void OnSPOUSE_FIRST_NAMEChanged();
    partial void OnMARITAL_STATUS_CODEChanging(string value);
    partial void OnMARITAL_STATUS_CODEChanged();
    partial void OnALLOW_ADVOCACY_FLAGChanging(System.Nullable<char> value);
    partial void OnALLOW_ADVOCACY_FLAGChanged();
    partial void OnCURRENCY_CODEChanging(string value);
    partial void OnCURRENCY_CODEChanged();
    partial void OnPRIMARY_SEARCH_GROUPChanging(string value);
    partial void OnPRIMARY_SEARCH_GROUPChanged();
    partial void OnUSR_CANDIDATE_ID_OVERRIDEChanging(string value);
    partial void OnUSR_CANDIDATE_ID_OVERRIDEChanged();
    partial void OnUSR_ALLOW_MARKETING_EMAILChanging(System.Nullable<char> value);
    partial void OnUSR_ALLOW_MARKETING_EMAILChanged();
    partial void OnUSR_HEAP_MASTERChanging(System.Nullable<char> value);
    partial void OnUSR_HEAP_MASTERChanged();
    partial void OnUSR_GRADUATION_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUSR_GRADUATION_DATEChanged();
    partial void OnUSR_FACEBOOK_UIDChanging(string value);
    partial void OnUSR_FACEBOOK_UIDChanged();
    partial void OnUSR_AVATARChanging(string value);
    partial void OnUSR_AVATARChanged();
    partial void OnUSR_FORUM_MEMBERChanging(System.Nullable<char> value);
    partial void OnUSR_FORUM_MEMBERChanged();
    partial void OnUSR_CUSTOMER_INFO_INCOMPLETEChanging(System.Nullable<char> value);
    partial void OnUSR_CUSTOMER_INFO_INCOMPLETEChanged();
    partial void OnUSR_FREE_MEMBERSHIP_UPGRADEChanging(System.Nullable<char> value);
    partial void OnUSR_FREE_MEMBERSHIP_UPGRADEChanged();
    partial void OnFAMILY_FLAGChanging(char value);
    partial void OnFAMILY_FLAGChanged();
    partial void OnPRIMARY_SEARCH_GROUP_OVERRIDE_FLAGChanging(System.Nullable<char> value);
    partial void OnPRIMARY_SEARCH_GROUP_OVERRIDE_FLAGChanged();
    partial void OnNAME_CREDENTIALS_DESCChanging(string value);
    partial void OnNAME_CREDENTIALS_DESCChanged();
    partial void OnPRIMARY_FAMILY_CONTACT_MAST_CUST_IDChanging(string value);
    partial void OnPRIMARY_FAMILY_CONTACT_MAST_CUST_IDChanged();
    partial void OnPRIMARY_FAMILY_CONTACT_SUB_CUST_IDChanging(System.Nullable<decimal> value);
    partial void OnPRIMARY_FAMILY_CONTACT_SUB_CUST_IDChanged();
    partial void OnINCLUDE_IN_WEB_MOBILE_DIRECTORY_FLAGChanging(char value);
    partial void OnINCLUDE_IN_WEB_MOBILE_DIRECTORY_FLAGChanged();
    partial void OnGUEST_CHECKOUT_FLAGChanging(char value);
    partial void OnGUEST_CHECKOUT_FLAGChanged();
    partial void OnUSR_TRAINING_BUDGET_SIZE_CODEChanging(string value);
    partial void OnUSR_TRAINING_BUDGET_SIZE_CODEChanged();
    partial void OnUSR_DIRECT_REPORT_COUNT_CODEChanging(string value);
    partial void OnUSR_DIRECT_REPORT_COUNT_CODEChanged();
    partial void OnUSR_SSO_USERNAMEChanging(string value);
    partial void OnUSR_SSO_USERNAMEChanged();
    partial void OnUSR_JOB_BANK_CODEChanging(string value);
    partial void OnUSR_JOB_BANK_CODEChanged();
    partial void OnUSR_FORUM_MEMBER_SINCEChanging(string value);
    partial void OnUSR_FORUM_MEMBER_SINCEChanged();
    partial void OnUSR_FORUM_PARTNER_CODEChanging(string value);
    partial void OnUSR_FORUM_PARTNER_CODEChanged();
    partial void OnUSR_SELECTED_TERMSCONDITIONSChanging(System.Nullable<System.DateTime> value);
    partial void OnUSR_SELECTED_TERMSCONDITIONSChanged();
    #endregion
		
		public CUSTOMER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASTER_CUSTOMER_ID", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASTER_CUSTOMER_ID
		{
			get
			{
				return this._MASTER_CUSTOMER_ID;
			}
			set
			{
				if ((this._MASTER_CUSTOMER_ID != value))
				{
					this.OnMASTER_CUSTOMER_IDChanging(value);
					this.SendPropertyChanging();
					this._MASTER_CUSTOMER_ID = value;
					this.SendPropertyChanged("MASTER_CUSTOMER_ID");
					this.OnMASTER_CUSTOMER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CUSTOMER_ID", DbType="Decimal(3,0) NOT NULL", IsPrimaryKey=true)]
		public decimal SUB_CUSTOMER_ID
		{
			get
			{
				return this._SUB_CUSTOMER_ID;
			}
			set
			{
				if ((this._SUB_CUSTOMER_ID != value))
				{
					this.OnSUB_CUSTOMER_IDChanging(value);
					this.SendPropertyChanging();
					this._SUB_CUSTOMER_ID = value;
					this.SendPropertyChanged("SUB_CUSTOMER_ID");
					this.OnSUB_CUSTOMER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORG_ID", DbType="VarChar(8)")]
		public string ORG_ID
		{
			get
			{
				return this._ORG_ID;
			}
			set
			{
				if ((this._ORG_ID != value))
				{
					this.OnORG_IDChanging(value);
					this.SendPropertyChanging();
					this._ORG_ID = value;
					this.SendPropertyChanged("ORG_ID");
					this.OnORG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORG_UNIT_ID", DbType="VarChar(8)")]
		public string ORG_UNIT_ID
		{
			get
			{
				return this._ORG_UNIT_ID;
			}
			set
			{
				if ((this._ORG_UNIT_ID != value))
				{
					this.OnORG_UNIT_IDChanging(value);
					this.SendPropertyChanging();
					this._ORG_UNIT_ID = value;
					this.SendPropertyChanged("ORG_UNIT_ID");
					this.OnORG_UNIT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORD_TYPE", DbType="Char(1) NOT NULL")]
		public char RECORD_TYPE
		{
			get
			{
				return this._RECORD_TYPE;
			}
			set
			{
				if ((this._RECORD_TYPE != value))
				{
					this.OnRECORD_TYPEChanging(value);
					this.SendPropertyChanging();
					this._RECORD_TYPE = value;
					this.SendPropertyChanged("RECORD_TYPE");
					this.OnRECORD_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEARCH_NAME", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string SEARCH_NAME
		{
			get
			{
				return this._SEARCH_NAME;
			}
			set
			{
				if ((this._SEARCH_NAME != value))
				{
					this.OnSEARCH_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SEARCH_NAME = value;
					this.SendPropertyChanged("SEARCH_NAME");
					this.OnSEARCH_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LABEL_NAME", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string LABEL_NAME
		{
			get
			{
				return this._LABEL_NAME;
			}
			set
			{
				if ((this._LABEL_NAME != value))
				{
					this.OnLABEL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LABEL_NAME = value;
					this.SendPropertyChanged("LABEL_NAME");
					this.OnLABEL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAN_PLACE_ORDER_FLAG", DbType="Char(1) NOT NULL")]
		public char CAN_PLACE_ORDER_FLAG
		{
			get
			{
				return this._CAN_PLACE_ORDER_FLAG;
			}
			set
			{
				if ((this._CAN_PLACE_ORDER_FLAG != value))
				{
					this.OnCAN_PLACE_ORDER_FLAGChanging(value);
					this.SendPropertyChanging();
					this._CAN_PLACE_ORDER_FLAG = value;
					this.SendPropertyChanged("CAN_PLACE_ORDER_FLAG");
					this.OnCAN_PLACE_ORDER_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BILL_PRIMARY_ACCOUNT_FLAG", DbType="Char(1) NOT NULL")]
		public char BILL_PRIMARY_ACCOUNT_FLAG
		{
			get
			{
				return this._BILL_PRIMARY_ACCOUNT_FLAG;
			}
			set
			{
				if ((this._BILL_PRIMARY_ACCOUNT_FLAG != value))
				{
					this.OnBILL_PRIMARY_ACCOUNT_FLAGChanging(value);
					this.SendPropertyChanging();
					this._BILL_PRIMARY_ACCOUNT_FLAG = value;
					this.SendPropertyChanged("BILL_PRIMARY_ACCOUNT_FLAG");
					this.OnBILL_PRIMARY_ACCOUNT_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_PREFIX", DbType="VarChar(20)")]
		public string NAME_PREFIX
		{
			get
			{
				return this._NAME_PREFIX;
			}
			set
			{
				if ((this._NAME_PREFIX != value))
				{
					this.OnNAME_PREFIXChanging(value);
					this.SendPropertyChanging();
					this._NAME_PREFIX = value;
					this.SendPropertyChanged("NAME_PREFIX");
					this.OnNAME_PREFIXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="VarChar(40)")]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this.OnFIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRST_NAME = value;
					this.SendPropertyChanged("FIRST_NAME");
					this.OnFIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIDDLE_NAME", DbType="VarChar(40)")]
		public string MIDDLE_NAME
		{
			get
			{
				return this._MIDDLE_NAME;
			}
			set
			{
				if ((this._MIDDLE_NAME != value))
				{
					this.OnMIDDLE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MIDDLE_NAME = value;
					this.SendPropertyChanged("MIDDLE_NAME");
					this.OnMIDDLE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NAME", DbType="VarChar(60)")]
		public string LAST_NAME
		{
			get
			{
				return this._LAST_NAME;
			}
			set
			{
				if ((this._LAST_NAME != value))
				{
					this.OnLAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_NAME = value;
					this.SendPropertyChanged("LAST_NAME");
					this.OnLAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_SUFFIX", DbType="VarChar(20)")]
		public string NAME_SUFFIX
		{
			get
			{
				return this._NAME_SUFFIX;
			}
			set
			{
				if ((this._NAME_SUFFIX != value))
				{
					this.OnNAME_SUFFIXChanging(value);
					this.SendPropertyChanging();
					this._NAME_SUFFIX = value;
					this.SendPropertyChanged("NAME_SUFFIX");
					this.OnNAME_SUFFIXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_CREDENTIALS", DbType="VarChar(40)")]
		public string NAME_CREDENTIALS
		{
			get
			{
				return this._NAME_CREDENTIALS;
			}
			set
			{
				if ((this._NAME_CREDENTIALS != value))
				{
					this.OnNAME_CREDENTIALSChanging(value);
					this.SendPropertyChanging();
					this._NAME_CREDENTIALS = value;
					this.SendPropertyChanged("NAME_CREDENTIALS");
					this.OnNAME_CREDENTIALSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NICKNAME", DbType="VarChar(40)")]
		public string NICKNAME
		{
			get
			{
				return this._NICKNAME;
			}
			set
			{
				if ((this._NICKNAME != value))
				{
					this.OnNICKNAMEChanging(value);
					this.SendPropertyChanging();
					this._NICKNAME = value;
					this.SendPropertyChanged("NICKNAME");
					this.OnNICKNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORMAL_SALUTATION", DbType="VarChar(80)")]
		public string FORMAL_SALUTATION
		{
			get
			{
				return this._FORMAL_SALUTATION;
			}
			set
			{
				if ((this._FORMAL_SALUTATION != value))
				{
					this.OnFORMAL_SALUTATIONChanging(value);
					this.SendPropertyChanging();
					this._FORMAL_SALUTATION = value;
					this.SendPropertyChanged("FORMAL_SALUTATION");
					this.OnFORMAL_SALUTATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFORMAL_SALUTATION", DbType="VarChar(40)")]
		public string INFORMAL_SALUTATION
		{
			get
			{
				return this._INFORMAL_SALUTATION;
			}
			set
			{
				if ((this._INFORMAL_SALUTATION != value))
				{
					this.OnINFORMAL_SALUTATIONChanging(value);
					this.SendPropertyChanging();
					this._INFORMAL_SALUTATION = value;
					this.SendPropertyChanged("INFORMAL_SALUTATION");
					this.OnINFORMAL_SALUTATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_CLASS_CODE", DbType="VarChar(24) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_CLASS_CODE
		{
			get
			{
				return this._CUSTOMER_CLASS_CODE;
			}
			set
			{
				if ((this._CUSTOMER_CLASS_CODE != value))
				{
					this.OnCUSTOMER_CLASS_CODEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_CLASS_CODE = value;
					this.SendPropertyChanged("CUSTOMER_CLASS_CODE");
					this.OnCUSTOMER_CLASS_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATUS_CODE", DbType="VarChar(24) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_STATUS_CODE
		{
			get
			{
				return this._CUSTOMER_STATUS_CODE;
			}
			set
			{
				if ((this._CUSTOMER_STATUS_CODE != value))
				{
					this.OnCUSTOMER_STATUS_CODEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_STATUS_CODE = value;
					this.SendPropertyChanged("CUSTOMER_STATUS_CODE");
					this.OnCUSTOMER_STATUS_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATUS_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CUSTOMER_STATUS_DATE
		{
			get
			{
				return this._CUSTOMER_STATUS_DATE;
			}
			set
			{
				if ((this._CUSTOMER_STATUS_DATE != value))
				{
					this.OnCUSTOMER_STATUS_DATEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_STATUS_DATE = value;
					this.SendPropertyChanged("CUSTOMER_STATUS_DATE");
					this.OnCUSTOMER_STATUS_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALLOW_FAX_FLAG", DbType="Char(1) NOT NULL")]
		public char ALLOW_FAX_FLAG
		{
			get
			{
				return this._ALLOW_FAX_FLAG;
			}
			set
			{
				if ((this._ALLOW_FAX_FLAG != value))
				{
					this.OnALLOW_FAX_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ALLOW_FAX_FLAG = value;
					this.SendPropertyChanged("ALLOW_FAX_FLAG");
					this.OnALLOW_FAX_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALLOW_EMAIL_FLAG", DbType="Char(1) NOT NULL")]
		public char ALLOW_EMAIL_FLAG
		{
			get
			{
				return this._ALLOW_EMAIL_FLAG;
			}
			set
			{
				if ((this._ALLOW_EMAIL_FLAG != value))
				{
					this.OnALLOW_EMAIL_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ALLOW_EMAIL_FLAG = value;
					this.SendPropertyChanged("ALLOW_EMAIL_FLAG");
					this.OnALLOW_EMAIL_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALLOW_PHONE_FLAG", DbType="Char(1) NOT NULL")]
		public char ALLOW_PHONE_FLAG
		{
			get
			{
				return this._ALLOW_PHONE_FLAG;
			}
			set
			{
				if ((this._ALLOW_PHONE_FLAG != value))
				{
					this.OnALLOW_PHONE_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ALLOW_PHONE_FLAG = value;
					this.SendPropertyChanged("ALLOW_PHONE_FLAG");
					this.OnALLOW_PHONE_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALLOW_LABEL_SALES_FLAG", DbType="Char(1) NOT NULL")]
		public char ALLOW_LABEL_SALES_FLAG
		{
			get
			{
				return this._ALLOW_LABEL_SALES_FLAG;
			}
			set
			{
				if ((this._ALLOW_LABEL_SALES_FLAG != value))
				{
					this.OnALLOW_LABEL_SALES_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ALLOW_LABEL_SALES_FLAG = value;
					this.SendPropertyChanged("ALLOW_LABEL_SALES_FLAG");
					this.OnALLOW_LABEL_SALES_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALLOW_SOLICITATION_FLAG", DbType="Char(1) NOT NULL")]
		public char ALLOW_SOLICITATION_FLAG
		{
			get
			{
				return this._ALLOW_SOLICITATION_FLAG;
			}
			set
			{
				if ((this._ALLOW_SOLICITATION_FLAG != value))
				{
					this.OnALLOW_SOLICITATION_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ALLOW_SOLICITATION_FLAG = value;
					this.SendPropertyChanged("ALLOW_SOLICITATION_FLAG");
					this.OnALLOW_SOLICITATION_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALLOW_INTERNAL_MAIL_FLAG", DbType="Char(1) NOT NULL")]
		public char ALLOW_INTERNAL_MAIL_FLAG
		{
			get
			{
				return this._ALLOW_INTERNAL_MAIL_FLAG;
			}
			set
			{
				if ((this._ALLOW_INTERNAL_MAIL_FLAG != value))
				{
					this.OnALLOW_INTERNAL_MAIL_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ALLOW_INTERNAL_MAIL_FLAG = value;
					this.SendPropertyChanged("ALLOW_INTERNAL_MAIL_FLAG");
					this.OnALLOW_INTERNAL_MAIL_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLICITATION_REMOVAL_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SOLICITATION_REMOVAL_DATE
		{
			get
			{
				return this._SOLICITATION_REMOVAL_DATE;
			}
			set
			{
				if ((this._SOLICITATION_REMOVAL_DATE != value))
				{
					this.OnSOLICITATION_REMOVAL_DATEChanging(value);
					this.SendPropertyChanging();
					this._SOLICITATION_REMOVAL_DATE = value;
					this.SendPropertyChanged("SOLICITATION_REMOVAL_DATE");
					this.OnSOLICITATION_REMOVAL_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXABLE_FLAG", DbType="Char(1) NOT NULL")]
		public char TAXABLE_FLAG
		{
			get
			{
				return this._TAXABLE_FLAG;
			}
			set
			{
				if ((this._TAXABLE_FLAG != value))
				{
					this.OnTAXABLE_FLAGChanging(value);
					this.SendPropertyChanging();
					this._TAXABLE_FLAG = value;
					this.SendPropertyChanged("TAXABLE_FLAG");
					this.OnTAXABLE_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEDERAL_TAX_ID", DbType="VarChar(11)")]
		public string FEDERAL_TAX_ID
		{
			get
			{
				return this._FEDERAL_TAX_ID;
			}
			set
			{
				if ((this._FEDERAL_TAX_ID != value))
				{
					this.OnFEDERAL_TAX_IDChanging(value);
					this.SendPropertyChanging();
					this._FEDERAL_TAX_ID = value;
					this.SendPropertyChanged("FEDERAL_TAX_ID");
					this.OnFEDERAL_TAX_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAT_ID", DbType="VarChar(30)")]
		public string VAT_ID
		{
			get
			{
				return this._VAT_ID;
			}
			set
			{
				if ((this._VAT_ID != value))
				{
					this.OnVAT_IDChanging(value);
					this.SendPropertyChanging();
					this._VAT_ID = value;
					this.SendPropertyChanged("VAT_ID");
					this.OnVAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAX_EXEMPT_ID", DbType="VarChar(11)")]
		public string TAX_EXEMPT_ID
		{
			get
			{
				return this._TAX_EXEMPT_ID;
			}
			set
			{
				if ((this._TAX_EXEMPT_ID != value))
				{
					this.OnTAX_EXEMPT_IDChanging(value);
					this.SendPropertyChanging();
					this._TAX_EXEMPT_ID = value;
					this.SendPropertyChanged("TAX_EXEMPT_ID");
					this.OnTAX_EXEMPT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="VarChar(11)")]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this.OnSSNChanging(value);
					this.SendPropertyChanging();
					this._SSN = value;
					this.SendPropertyChanged("SSN");
					this.OnSSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_CODE", DbType="VarChar(24)")]
		public string GENDER_CODE
		{
			get
			{
				return this._GENDER_CODE;
			}
			set
			{
				if ((this._GENDER_CODE != value))
				{
					this.OnGENDER_CODEChanging(value);
					this.SendPropertyChanging();
					this._GENDER_CODE = value;
					this.SendPropertyChanged("GENDER_CODE");
					this.OnGENDER_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this.OnBIRTH_DATEChanging(value);
					this.SendPropertyChanging();
					this._BIRTH_DATE = value;
					this.SendPropertyChanged("BIRTH_DATE");
					this.OnBIRTH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETHNICITY_CODE", DbType="VarChar(24)")]
		public string ETHNICITY_CODE
		{
			get
			{
				return this._ETHNICITY_CODE;
			}
			set
			{
				if ((this._ETHNICITY_CODE != value))
				{
					this.OnETHNICITY_CODEChanging(value);
					this.SendPropertyChanging();
					this._ETHNICITY_CODE = value;
					this.SendPropertyChanged("ETHNICITY_CODE");
					this.OnETHNICITY_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANNUAL_INCOME_RANGE_CODE", DbType="VarChar(24)")]
		public string ANNUAL_INCOME_RANGE_CODE
		{
			get
			{
				return this._ANNUAL_INCOME_RANGE_CODE;
			}
			set
			{
				if ((this._ANNUAL_INCOME_RANGE_CODE != value))
				{
					this.OnANNUAL_INCOME_RANGE_CODEChanging(value);
					this.SendPropertyChanging();
					this._ANNUAL_INCOME_RANGE_CODE = value;
					this.SendPropertyChanged("ANNUAL_INCOME_RANGE_CODE");
					this.OnANNUAL_INCOME_RANGE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_FUNCTION_CODE", DbType="VarChar(24)")]
		public string JOB_FUNCTION_CODE
		{
			get
			{
				return this._JOB_FUNCTION_CODE;
			}
			set
			{
				if ((this._JOB_FUNCTION_CODE != value))
				{
					this.OnJOB_FUNCTION_CODEChanging(value);
					this.SendPropertyChanging();
					this._JOB_FUNCTION_CODE = value;
					this.SendPropertyChanged("JOB_FUNCTION_CODE");
					this.OnJOB_FUNCTION_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVENUE_RANGE_CODE", DbType="VarChar(24)")]
		public string REVENUE_RANGE_CODE
		{
			get
			{
				return this._REVENUE_RANGE_CODE;
			}
			set
			{
				if ((this._REVENUE_RANGE_CODE != value))
				{
					this.OnREVENUE_RANGE_CODEChanging(value);
					this.SendPropertyChanging();
					this._REVENUE_RANGE_CODE = value;
					this.SendPropertyChanged("REVENUE_RANGE_CODE");
					this.OnREVENUE_RANGE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_RANGE_CODE", DbType="VarChar(24)")]
		public string STAFF_RANGE_CODE
		{
			get
			{
				return this._STAFF_RANGE_CODE;
			}
			set
			{
				if ((this._STAFF_RANGE_CODE != value))
				{
					this.OnSTAFF_RANGE_CODEChanging(value);
					this.SendPropertyChanging();
					this._STAFF_RANGE_CODE = value;
					this.SendPropertyChanged("STAFF_RANGE_CODE");
					this.OnSTAFF_RANGE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOUNDATION_FLAG", DbType="Char(1)")]
		public System.Nullable<char> FOUNDATION_FLAG
		{
			get
			{
				return this._FOUNDATION_FLAG;
			}
			set
			{
				if ((this._FOUNDATION_FLAG != value))
				{
					this.OnFOUNDATION_FLAGChanging(value);
					this.SendPropertyChanging();
					this._FOUNDATION_FLAG = value;
					this.SendPropertyChanged("FOUNDATION_FLAG");
					this.OnFOUNDATION_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FND_MATCHING_FLAG", DbType="Char(1)")]
		public System.Nullable<char> FND_MATCHING_FLAG
		{
			get
			{
				return this._FND_MATCHING_FLAG;
			}
			set
			{
				if ((this._FND_MATCHING_FLAG != value))
				{
					this.OnFND_MATCHING_FLAGChanging(value);
					this.SendPropertyChanging();
					this._FND_MATCHING_FLAG = value;
					this.SendPropertyChanged("FND_MATCHING_FLAG");
					this.OnFND_MATCHING_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FND_MATCHING_PERCENT", DbType="Decimal(6,3)")]
		public System.Nullable<decimal> FND_MATCHING_PERCENT
		{
			get
			{
				return this._FND_MATCHING_PERCENT;
			}
			set
			{
				if ((this._FND_MATCHING_PERCENT != value))
				{
					this.OnFND_MATCHING_PERCENTChanging(value);
					this.SendPropertyChanging();
					this._FND_MATCHING_PERCENT = value;
					this.SendPropertyChanged("FND_MATCHING_PERCENT");
					this.OnFND_MATCHING_PERCENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FND_MATCHING_LIMIT", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> FND_MATCHING_LIMIT
		{
			get
			{
				return this._FND_MATCHING_LIMIT;
			}
			set
			{
				if ((this._FND_MATCHING_LIMIT != value))
				{
					this.OnFND_MATCHING_LIMITChanging(value);
					this.SendPropertyChanging();
					this._FND_MATCHING_LIMIT = value;
					this.SendPropertyChanged("FND_MATCHING_LIMIT");
					this.OnFND_MATCHING_LIMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIST_CODE", DbType="VarChar(24)")]
		public string LIST_CODE
		{
			get
			{
				return this._LIST_CODE;
			}
			set
			{
				if ((this._LIST_CODE != value))
				{
					this.OnLIST_CODEChanging(value);
					this.SendPropertyChanging();
					this._LIST_CODE = value;
					this.SendPropertyChanged("LIST_CODE");
					this.OnLIST_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENFORCE_COM_STRUCT_FLAG", DbType="Char(1) NOT NULL")]
		public char ENFORCE_COM_STRUCT_FLAG
		{
			get
			{
				return this._ENFORCE_COM_STRUCT_FLAG;
			}
			set
			{
				if ((this._ENFORCE_COM_STRUCT_FLAG != value))
				{
					this.OnENFORCE_COM_STRUCT_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ENFORCE_COM_STRUCT_FLAG = value;
					this.SendPropertyChanged("ENFORCE_COM_STRUCT_FLAG");
					this.OnENFORCE_COM_STRUCT_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOT_A_DUPLICATE_FLAG", DbType="Char(1) NOT NULL")]
		public char NOT_A_DUPLICATE_FLAG
		{
			get
			{
				return this._NOT_A_DUPLICATE_FLAG;
			}
			set
			{
				if ((this._NOT_A_DUPLICATE_FLAG != value))
				{
					this.OnNOT_A_DUPLICATE_FLAGChanging(value);
					this.SendPropertyChanging();
					this._NOT_A_DUPLICATE_FLAG = value;
					this.SendPropertyChanged("NOT_A_DUPLICATE_FLAG");
					this.OnNOT_A_DUPLICATE_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MERGED_TO_MAST_CUST", DbType="VarChar(12)")]
		public string MERGED_TO_MAST_CUST
		{
			get
			{
				return this._MERGED_TO_MAST_CUST;
			}
			set
			{
				if ((this._MERGED_TO_MAST_CUST != value))
				{
					this.OnMERGED_TO_MAST_CUSTChanging(value);
					this.SendPropertyChanging();
					this._MERGED_TO_MAST_CUST = value;
					this.SendPropertyChanged("MERGED_TO_MAST_CUST");
					this.OnMERGED_TO_MAST_CUSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MERGED_TO_SUB_CUST", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> MERGED_TO_SUB_CUST
		{
			get
			{
				return this._MERGED_TO_SUB_CUST;
			}
			set
			{
				if ((this._MERGED_TO_SUB_CUST != value))
				{
					this.OnMERGED_TO_SUB_CUSTChanging(value);
					this.SendPropertyChanging();
					this._MERGED_TO_SUB_CUST = value;
					this.SendPropertyChanged("MERGED_TO_SUB_CUST");
					this.OnMERGED_TO_SUB_CUSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXHIBITOR_FLAG", DbType="Char(1) NOT NULL")]
		public char EXHIBITOR_FLAG
		{
			get
			{
				return this._EXHIBITOR_FLAG;
			}
			set
			{
				if ((this._EXHIBITOR_FLAG != value))
				{
					this.OnEXHIBITOR_FLAGChanging(value);
					this.SendPropertyChanging();
					this._EXHIBITOR_FLAG = value;
					this.SendPropertyChanged("EXHIBITOR_FLAG");
					this.OnEXHIBITOR_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIP_COMMITTEE_PRIORITY", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> VIP_COMMITTEE_PRIORITY
		{
			get
			{
				return this._VIP_COMMITTEE_PRIORITY;
			}
			set
			{
				if ((this._VIP_COMMITTEE_PRIORITY != value))
				{
					this.OnVIP_COMMITTEE_PRIORITYChanging(value);
					this.SendPropertyChanging();
					this._VIP_COMMITTEE_PRIORITY = value;
					this.SendPropertyChanged("VIP_COMMITTEE_PRIORITY");
					this.OnVIP_COMMITTEE_PRIORITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOME_PHONE", DbType="VarChar(100)")]
		public string HOME_PHONE
		{
			get
			{
				return this._HOME_PHONE;
			}
			set
			{
				if ((this._HOME_PHONE != value))
				{
					this.OnHOME_PHONEChanging(value);
					this.SendPropertyChanging();
					this._HOME_PHONE = value;
					this.SendPropertyChanged("HOME_PHONE");
					this.OnHOME_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_PHONE", DbType="VarChar(100)")]
		public string WORK_PHONE
		{
			get
			{
				return this._WORK_PHONE;
			}
			set
			{
				if ((this._WORK_PHONE != value))
				{
					this.OnWORK_PHONEChanging(value);
					this.SendPropertyChanging();
					this._WORK_PHONE = value;
					this.SendPropertyChanged("WORK_PHONE");
					this.OnWORK_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_PHONE", DbType="VarChar(100)")]
		public string PRIMARY_PHONE
		{
			get
			{
				return this._PRIMARY_PHONE;
			}
			set
			{
				if ((this._PRIMARY_PHONE != value))
				{
					this.OnPRIMARY_PHONEChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_PHONE = value;
					this.SendPropertyChanged("PRIMARY_PHONE");
					this.OnPRIMARY_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_FAX", DbType="VarChar(100)")]
		public string PRIMARY_FAX
		{
			get
			{
				return this._PRIMARY_FAX;
			}
			set
			{
				if ((this._PRIMARY_FAX != value))
				{
					this.OnPRIMARY_FAXChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_FAX = value;
					this.SendPropertyChanged("PRIMARY_FAX");
					this.OnPRIMARY_FAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_EMAIL_ADDRESS", DbType="VarChar(100)")]
		public string PRIMARY_EMAIL_ADDRESS
		{
			get
			{
				return this._PRIMARY_EMAIL_ADDRESS;
			}
			set
			{
				if ((this._PRIMARY_EMAIL_ADDRESS != value))
				{
					this.OnPRIMARY_EMAIL_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_EMAIL_ADDRESS = value;
					this.SendPropertyChanged("PRIMARY_EMAIL_ADDRESS");
					this.OnPRIMARY_EMAIL_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_URL", DbType="VarChar(100)")]
		public string PRIMARY_URL
		{
			get
			{
				return this._PRIMARY_URL;
			}
			set
			{
				if ((this._PRIMARY_URL != value))
				{
					this.OnPRIMARY_URLChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_URL = value;
					this.SendPropertyChanged("PRIMARY_URL");
					this.OnPRIMARY_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_JOB_TITLE", DbType="VarChar(80)")]
		public string PRIMARY_JOB_TITLE
		{
			get
			{
				return this._PRIMARY_JOB_TITLE;
			}
			set
			{
				if ((this._PRIMARY_JOB_TITLE != value))
				{
					this.OnPRIMARY_JOB_TITLEChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_JOB_TITLE = value;
					this.SendPropertyChanged("PRIMARY_JOB_TITLE");
					this.OnPRIMARY_JOB_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_PHONE_LOCATION_CODE", DbType="VarChar(24)")]
		public string PRIMARY_PHONE_LOCATION_CODE
		{
			get
			{
				return this._PRIMARY_PHONE_LOCATION_CODE;
			}
			set
			{
				if ((this._PRIMARY_PHONE_LOCATION_CODE != value))
				{
					this.OnPRIMARY_PHONE_LOCATION_CODEChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_PHONE_LOCATION_CODE = value;
					this.SendPropertyChanged("PRIMARY_PHONE_LOCATION_CODE");
					this.OnPRIMARY_PHONE_LOCATION_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_EMAIL_LOCATION_CODE", DbType="VarChar(24)")]
		public string PRIMARY_EMAIL_LOCATION_CODE
		{
			get
			{
				return this._PRIMARY_EMAIL_LOCATION_CODE;
			}
			set
			{
				if ((this._PRIMARY_EMAIL_LOCATION_CODE != value))
				{
					this.OnPRIMARY_EMAIL_LOCATION_CODEChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_EMAIL_LOCATION_CODE = value;
					this.SendPropertyChanged("PRIMARY_EMAIL_LOCATION_CODE");
					this.OnPRIMARY_EMAIL_LOCATION_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_FAX_LOCATION_CODE", DbType="VarChar(24)")]
		public string PRIMARY_FAX_LOCATION_CODE
		{
			get
			{
				return this._PRIMARY_FAX_LOCATION_CODE;
			}
			set
			{
				if ((this._PRIMARY_FAX_LOCATION_CODE != value))
				{
					this.OnPRIMARY_FAX_LOCATION_CODEChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_FAX_LOCATION_CODE = value;
					this.SendPropertyChanged("PRIMARY_FAX_LOCATION_CODE");
					this.OnPRIMARY_FAX_LOCATION_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUBLISH_PRIMARY_FAX_FLAG", DbType="Char(1)")]
		public System.Nullable<char> PUBLISH_PRIMARY_FAX_FLAG
		{
			get
			{
				return this._PUBLISH_PRIMARY_FAX_FLAG;
			}
			set
			{
				if ((this._PUBLISH_PRIMARY_FAX_FLAG != value))
				{
					this.OnPUBLISH_PRIMARY_FAX_FLAGChanging(value);
					this.SendPropertyChanging();
					this._PUBLISH_PRIMARY_FAX_FLAG = value;
					this.SendPropertyChanged("PUBLISH_PRIMARY_FAX_FLAG");
					this.OnPUBLISH_PRIMARY_FAX_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUBLISH_PRIMARY_PHONE_FLAG", DbType="Char(1)")]
		public System.Nullable<char> PUBLISH_PRIMARY_PHONE_FLAG
		{
			get
			{
				return this._PUBLISH_PRIMARY_PHONE_FLAG;
			}
			set
			{
				if ((this._PUBLISH_PRIMARY_PHONE_FLAG != value))
				{
					this.OnPUBLISH_PRIMARY_PHONE_FLAGChanging(value);
					this.SendPropertyChanging();
					this._PUBLISH_PRIMARY_PHONE_FLAG = value;
					this.SendPropertyChanged("PUBLISH_PRIMARY_PHONE_FLAG");
					this.OnPUBLISH_PRIMARY_PHONE_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUBLISH_PRIMARY_EMAIL_FLAG", DbType="Char(1)")]
		public System.Nullable<char> PUBLISH_PRIMARY_EMAIL_FLAG
		{
			get
			{
				return this._PUBLISH_PRIMARY_EMAIL_FLAG;
			}
			set
			{
				if ((this._PUBLISH_PRIMARY_EMAIL_FLAG != value))
				{
					this.OnPUBLISH_PRIMARY_EMAIL_FLAGChanging(value);
					this.SendPropertyChanging();
					this._PUBLISH_PRIMARY_EMAIL_FLAG = value;
					this.SendPropertyChanged("PUBLISH_PRIMARY_EMAIL_FLAG");
					this.OnPUBLISH_PRIMARY_EMAIL_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUBLISH_HOME_PHONE_FLAG", DbType="Char(1)")]
		public System.Nullable<char> PUBLISH_HOME_PHONE_FLAG
		{
			get
			{
				return this._PUBLISH_HOME_PHONE_FLAG;
			}
			set
			{
				if ((this._PUBLISH_HOME_PHONE_FLAG != value))
				{
					this.OnPUBLISH_HOME_PHONE_FLAGChanging(value);
					this.SendPropertyChanging();
					this._PUBLISH_HOME_PHONE_FLAG = value;
					this.SendPropertyChanged("PUBLISH_HOME_PHONE_FLAG");
					this.OnPUBLISH_HOME_PHONE_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUBLISH_WORK_PHONE_FLAG", DbType="Char(1)")]
		public System.Nullable<char> PUBLISH_WORK_PHONE_FLAG
		{
			get
			{
				return this._PUBLISH_WORK_PHONE_FLAG;
			}
			set
			{
				if ((this._PUBLISH_WORK_PHONE_FLAG != value))
				{
					this.OnPUBLISH_WORK_PHONE_FLAGChanging(value);
					this.SendPropertyChanging();
					this._PUBLISH_WORK_PHONE_FLAG = value;
					this.SendPropertyChanged("PUBLISH_WORK_PHONE_FLAG");
					this.OnPUBLISH_WORK_PHONE_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEFAULT_LANGUAGE_CODE", DbType="VarChar(6)")]
		public string DEFAULT_LANGUAGE_CODE
		{
			get
			{
				return this._DEFAULT_LANGUAGE_CODE;
			}
			set
			{
				if ((this._DEFAULT_LANGUAGE_CODE != value))
				{
					this.OnDEFAULT_LANGUAGE_CODEChanging(value);
					this.SendPropertyChanging();
					this._DEFAULT_LANGUAGE_CODE = value;
					this.SendPropertyChanged("DEFAULT_LANGUAGE_CODE");
					this.OnDEFAULT_LANGUAGE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDOPER", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ADDOPER
		{
			get
			{
				return this._ADDOPER;
			}
			set
			{
				if ((this._ADDOPER != value))
				{
					this.OnADDOPERChanging(value);
					this.SendPropertyChanging();
					this._ADDOPER = value;
					this.SendPropertyChanged("ADDOPER");
					this.OnADDOPERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDDATE", DbType="DateTime NOT NULL")]
		public System.DateTime ADDDATE
		{
			get
			{
				return this._ADDDATE;
			}
			set
			{
				if ((this._ADDDATE != value))
				{
					this.OnADDDATEChanging(value);
					this.SendPropertyChanging();
					this._ADDDATE = value;
					this.SendPropertyChanged("ADDDATE");
					this.OnADDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODOPER", DbType="VarChar(20)")]
		public string MODOPER
		{
			get
			{
				return this._MODOPER;
			}
			set
			{
				if ((this._MODOPER != value))
				{
					this.OnMODOPERChanging(value);
					this.SendPropertyChanging();
					this._MODOPER = value;
					this.SendPropertyChanged("MODOPER");
					this.OnMODOPERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODDATE
		{
			get
			{
				return this._MODDATE;
			}
			set
			{
				if ((this._MODDATE != value))
				{
					this.OnMODDATEChanging(value);
					this.SendPropertyChanging();
					this._MODDATE = value;
					this.SendPropertyChanged("MODDATE");
					this.OnMODDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONCURRENCY_ID", DbType="Decimal(12,0) NOT NULL")]
		public decimal CONCURRENCY_ID
		{
			get
			{
				return this._CONCURRENCY_ID;
			}
			set
			{
				if ((this._CONCURRENCY_ID != value))
				{
					this.OnCONCURRENCY_IDChanging(value);
					this.SendPropertyChanging();
					this._CONCURRENCY_ID = value;
					this.SendPropertyChanged("CONCURRENCY_ID");
					this.OnCONCURRENCY_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE_ID", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> IMAGE_ID
		{
			get
			{
				return this._IMAGE_ID;
			}
			set
			{
				if ((this._IMAGE_ID != value))
				{
					this.OnIMAGE_IDChanging(value);
					this.SendPropertyChanging();
					this._IMAGE_ID = value;
					this.SendPropertyChanged("IMAGE_ID");
					this.OnIMAGE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREFERRED_COMM_METHOD_CODE", DbType="VarChar(24)")]
		public string PREFERRED_COMM_METHOD_CODE
		{
			get
			{
				return this._PREFERRED_COMM_METHOD_CODE;
			}
			set
			{
				if ((this._PREFERRED_COMM_METHOD_CODE != value))
				{
					this.OnPREFERRED_COMM_METHOD_CODEChanging(value);
					this.SendPropertyChanging();
					this._PREFERRED_COMM_METHOD_CODE = value;
					this.SendPropertyChanged("PREFERRED_COMM_METHOD_CODE");
					this.OnPREFERRED_COMM_METHOD_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BILL_PRIMARY_EMPLOYER_FLAG", DbType="Char(1)")]
		public System.Nullable<char> BILL_PRIMARY_EMPLOYER_FLAG
		{
			get
			{
				return this._BILL_PRIMARY_EMPLOYER_FLAG;
			}
			set
			{
				if ((this._BILL_PRIMARY_EMPLOYER_FLAG != value))
				{
					this.OnBILL_PRIMARY_EMPLOYER_FLAGChanging(value);
					this.SendPropertyChanging();
					this._BILL_PRIMARY_EMPLOYER_FLAG = value;
					this.SendPropertyChanged("BILL_PRIMARY_EMPLOYER_FLAG");
					this.OnBILL_PRIMARY_EMPLOYER_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_FIRST_NAME", DbType="VarChar(80)")]
		public string LAST_FIRST_NAME
		{
			get
			{
				return this._LAST_FIRST_NAME;
			}
			set
			{
				if ((this._LAST_FIRST_NAME != value))
				{
					this.OnLAST_FIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_FIRST_NAME = value;
					this.SendPropertyChanged("LAST_FIRST_NAME");
					this.OnLAST_FIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRN_COUNTRY_CODE", DbType="VarChar(24)")]
		public string TRN_COUNTRY_CODE
		{
			get
			{
				return this._TRN_COUNTRY_CODE;
			}
			set
			{
				if ((this._TRN_COUNTRY_CODE != value))
				{
					this.OnTRN_COUNTRY_CODEChanging(value);
					this.SendPropertyChanging();
					this._TRN_COUNTRY_CODE = value;
					this.SendPropertyChanged("TRN_COUNTRY_CODE");
					this.OnTRN_COUNTRY_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRN_STATE_CODE", DbType="VarChar(40)")]
		public string TRN_STATE_CODE
		{
			get
			{
				return this._TRN_STATE_CODE;
			}
			set
			{
				if ((this._TRN_STATE_CODE != value))
				{
					this.OnTRN_STATE_CODEChanging(value);
					this.SendPropertyChanging();
					this._TRN_STATE_CODE = value;
					this.SendPropertyChanged("TRN_STATE_CODE");
					this.OnTRN_STATE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORIG_CUS_ADDRESS_ID", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> ORIG_CUS_ADDRESS_ID
		{
			get
			{
				return this._ORIG_CUS_ADDRESS_ID;
			}
			set
			{
				if ((this._ORIG_CUS_ADDRESS_ID != value))
				{
					this.OnORIG_CUS_ADDRESS_IDChanging(value);
					this.SendPropertyChanging();
					this._ORIG_CUS_ADDRESS_ID = value;
					this.SendPropertyChanged("ORIG_CUS_ADDRESS_ID");
					this.OnORIG_CUS_ADDRESS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORIG_CUS_ADDRESS_TYPE_CODE", DbType="VarChar(24)")]
		public string ORIG_CUS_ADDRESS_TYPE_CODE
		{
			get
			{
				return this._ORIG_CUS_ADDRESS_TYPE_CODE;
			}
			set
			{
				if ((this._ORIG_CUS_ADDRESS_TYPE_CODE != value))
				{
					this.OnORIG_CUS_ADDRESS_TYPE_CODEChanging(value);
					this.SendPropertyChanging();
					this._ORIG_CUS_ADDRESS_TYPE_CODE = value;
					this.SendPropertyChanged("ORIG_CUS_ADDRESS_TYPE_CODE");
					this.OnORIG_CUS_ADDRESS_TYPE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEB_SEGMENT_CREATION_FLAG", DbType="Char(1) NOT NULL")]
		public char WEB_SEGMENT_CREATION_FLAG
		{
			get
			{
				return this._WEB_SEGMENT_CREATION_FLAG;
			}
			set
			{
				if ((this._WEB_SEGMENT_CREATION_FLAG != value))
				{
					this.OnWEB_SEGMENT_CREATION_FLAGChanging(value);
					this.SendPropertyChanging();
					this._WEB_SEGMENT_CREATION_FLAG = value;
					this.SendPropertyChanged("WEB_SEGMENT_CREATION_FLAG");
					this.OnWEB_SEGMENT_CREATION_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGMENT_RULE_CODE", DbType="VarChar(24)")]
		public string SEGMENT_RULE_CODE
		{
			get
			{
				return this._SEGMENT_RULE_CODE;
			}
			set
			{
				if ((this._SEGMENT_RULE_CODE != value))
				{
					this.OnSEGMENT_RULE_CODEChanging(value);
					this.SendPropertyChanging();
					this._SEGMENT_RULE_CODE = value;
					this.SendPropertyChanged("SEGMENT_RULE_CODE");
					this.OnSEGMENT_RULE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGMENT_QUALIFIER1", DbType="VarChar(50)")]
		public string SEGMENT_QUALIFIER1
		{
			get
			{
				return this._SEGMENT_QUALIFIER1;
			}
			set
			{
				if ((this._SEGMENT_QUALIFIER1 != value))
				{
					this.OnSEGMENT_QUALIFIER1Changing(value);
					this.SendPropertyChanging();
					this._SEGMENT_QUALIFIER1 = value;
					this.SendPropertyChanged("SEGMENT_QUALIFIER1");
					this.OnSEGMENT_QUALIFIER1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGMENT_QUALIFIER2", DbType="VarChar(50)")]
		public string SEGMENT_QUALIFIER2
		{
			get
			{
				return this._SEGMENT_QUALIFIER2;
			}
			set
			{
				if ((this._SEGMENT_QUALIFIER2 != value))
				{
					this.OnSEGMENT_QUALIFIER2Changing(value);
					this.SendPropertyChanging();
					this._SEGMENT_QUALIFIER2 = value;
					this.SendPropertyChanged("SEGMENT_QUALIFIER2");
					this.OnSEGMENT_QUALIFIER2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INCLUDE_IN_DIRECTORY_FLAG", DbType="Char(1)")]
		public System.Nullable<char> INCLUDE_IN_DIRECTORY_FLAG
		{
			get
			{
				return this._INCLUDE_IN_DIRECTORY_FLAG;
			}
			set
			{
				if ((this._INCLUDE_IN_DIRECTORY_FLAG != value))
				{
					this.OnINCLUDE_IN_DIRECTORY_FLAGChanging(value);
					this.SendPropertyChanging();
					this._INCLUDE_IN_DIRECTORY_FLAG = value;
					this.SendPropertyChanged("INCLUDE_IN_DIRECTORY_FLAG");
					this.OnINCLUDE_IN_DIRECTORY_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGMENT_DESCR", DbType="VarChar(255)")]
		public string SEGMENT_DESCR
		{
			get
			{
				return this._SEGMENT_DESCR;
			}
			set
			{
				if ((this._SEGMENT_DESCR != value))
				{
					this.OnSEGMENT_DESCRChanging(value);
					this.SendPropertyChanging();
					this._SEGMENT_DESCR = value;
					this.SendPropertyChanged("SEGMENT_DESCR");
					this.OnSEGMENT_DESCRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAN_CREATE_SEGMENTS_FLAG", DbType="Char(1) NOT NULL")]
		public char CAN_CREATE_SEGMENTS_FLAG
		{
			get
			{
				return this._CAN_CREATE_SEGMENTS_FLAG;
			}
			set
			{
				if ((this._CAN_CREATE_SEGMENTS_FLAG != value))
				{
					this.OnCAN_CREATE_SEGMENTS_FLAGChanging(value);
					this.SendPropertyChanging();
					this._CAN_CREATE_SEGMENTS_FLAG = value;
					this.SendPropertyChanged("CAN_CREATE_SEGMENTS_FLAG");
					this.OnCAN_CREATE_SEGMENTS_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_VENDOR_NO", DbType="VarChar(100)")]
		public string USR_VENDOR_NO
		{
			get
			{
				return this._USR_VENDOR_NO;
			}
			set
			{
				if ((this._USR_VENDOR_NO != value))
				{
					this.OnUSR_VENDOR_NOChanging(value);
					this.SendPropertyChanging();
					this._USR_VENDOR_NO = value;
					this.SendPropertyChanged("USR_VENDOR_NO");
					this.OnUSR_VENDOR_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_JOB_TITLE_CODE", DbType="VarChar(24)")]
		public string USR_JOB_TITLE_CODE
		{
			get
			{
				return this._USR_JOB_TITLE_CODE;
			}
			set
			{
				if ((this._USR_JOB_TITLE_CODE != value))
				{
					this.OnUSR_JOB_TITLE_CODEChanging(value);
					this.SendPropertyChanging();
					this._USR_JOB_TITLE_CODE = value;
					this.SendPropertyChanged("USR_JOB_TITLE_CODE");
					this.OnUSR_JOB_TITLE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_INDUSTRY_CODE", DbType="VarChar(24)")]
		public string USR_INDUSTRY_CODE
		{
			get
			{
				return this._USR_INDUSTRY_CODE;
			}
			set
			{
				if ((this._USR_INDUSTRY_CODE != value))
				{
					this.OnUSR_INDUSTRY_CODEChanging(value);
					this.SendPropertyChanging();
					this._USR_INDUSTRY_CODE = value;
					this.SendPropertyChanged("USR_INDUSTRY_CODE");
					this.OnUSR_INDUSTRY_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_SIC_CODE", DbType="VarChar(24)")]
		public string USR_SIC_CODE
		{
			get
			{
				return this._USR_SIC_CODE;
			}
			set
			{
				if ((this._USR_SIC_CODE != value))
				{
					this.OnUSR_SIC_CODEChanging(value);
					this.SendPropertyChanging();
					this._USR_SIC_CODE = value;
					this.SendPropertyChanged("USR_SIC_CODE");
					this.OnUSR_SIC_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_JOB_FUNCTION_CODE", DbType="VarChar(24)")]
		public string USR_JOB_FUNCTION_CODE
		{
			get
			{
				return this._USR_JOB_FUNCTION_CODE;
			}
			set
			{
				if ((this._USR_JOB_FUNCTION_CODE != value))
				{
					this.OnUSR_JOB_FUNCTION_CODEChanging(value);
					this.SendPropertyChanging();
					this._USR_JOB_FUNCTION_CODE = value;
					this.SendPropertyChanged("USR_JOB_FUNCTION_CODE");
					this.OnUSR_JOB_FUNCTION_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_COMPANY_SIZE_CODE", DbType="VarChar(24)")]
		public string USR_COMPANY_SIZE_CODE
		{
			get
			{
				return this._USR_COMPANY_SIZE_CODE;
			}
			set
			{
				if ((this._USR_COMPANY_SIZE_CODE != value))
				{
					this.OnUSR_COMPANY_SIZE_CODEChanging(value);
					this.SendPropertyChanging();
					this._USR_COMPANY_SIZE_CODE = value;
					this.SendPropertyChanged("USR_COMPANY_SIZE_CODE");
					this.OnUSR_COMPANY_SIZE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_MEMBER_DIRECTORY", DbType="Char(1) NOT NULL")]
		public char USR_MEMBER_DIRECTORY
		{
			get
			{
				return this._USR_MEMBER_DIRECTORY;
			}
			set
			{
				if ((this._USR_MEMBER_DIRECTORY != value))
				{
					this.OnUSR_MEMBER_DIRECTORYChanging(value);
					this.SendPropertyChanging();
					this._USR_MEMBER_DIRECTORY = value;
					this.SendPropertyChanged("USR_MEMBER_DIRECTORY");
					this.OnUSR_MEMBER_DIRECTORYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAILING_PER_YEAR", DbType="Int")]
		public System.Nullable<int> MAILING_PER_YEAR
		{
			get
			{
				return this._MAILING_PER_YEAR;
			}
			set
			{
				if ((this._MAILING_PER_YEAR != value))
				{
					this.OnMAILING_PER_YEARChanging(value);
					this.SendPropertyChanging();
					this._MAILING_PER_YEAR = value;
					this.SendPropertyChanged("MAILING_PER_YEAR");
					this.OnMAILING_PER_YEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_CONTACT_MAST_CUST_ID", DbType="VarChar(12)")]
		public string PRIMARY_CONTACT_MAST_CUST_ID
		{
			get
			{
				return this._PRIMARY_CONTACT_MAST_CUST_ID;
			}
			set
			{
				if ((this._PRIMARY_CONTACT_MAST_CUST_ID != value))
				{
					this.OnPRIMARY_CONTACT_MAST_CUST_IDChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_CONTACT_MAST_CUST_ID = value;
					this.SendPropertyChanged("PRIMARY_CONTACT_MAST_CUST_ID");
					this.OnPRIMARY_CONTACT_MAST_CUST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_CONTACT_SUB_CUST_ID", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> PRIMARY_CONTACT_SUB_CUST_ID
		{
			get
			{
				return this._PRIMARY_CONTACT_SUB_CUST_ID;
			}
			set
			{
				if ((this._PRIMARY_CONTACT_SUB_CUST_ID != value))
				{
					this.OnPRIMARY_CONTACT_SUB_CUST_IDChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_CONTACT_SUB_CUST_ID = value;
					this.SendPropertyChanged("PRIMARY_CONTACT_SUB_CUST_ID");
					this.OnPRIMARY_CONTACT_SUB_CUST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHORT_NAME_CODE", DbType="VarChar(24)")]
		public string SHORT_NAME_CODE
		{
			get
			{
				return this._SHORT_NAME_CODE;
			}
			set
			{
				if ((this._SHORT_NAME_CODE != value))
				{
					this.OnSHORT_NAME_CODEChanging(value);
					this.SendPropertyChanging();
					this._SHORT_NAME_CODE = value;
					this.SendPropertyChanged("SHORT_NAME_CODE");
					this.OnSHORT_NAME_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFICIAL_COMMITTEE_FLAG", DbType="Char(1) NOT NULL")]
		public char OFFICIAL_COMMITTEE_FLAG
		{
			get
			{
				return this._OFFICIAL_COMMITTEE_FLAG;
			}
			set
			{
				if ((this._OFFICIAL_COMMITTEE_FLAG != value))
				{
					this.OnOFFICIAL_COMMITTEE_FLAGChanging(value);
					this.SendPropertyChanging();
					this._OFFICIAL_COMMITTEE_FLAG = value;
					this.SendPropertyChanged("OFFICIAL_COMMITTEE_FLAG");
					this.OnOFFICIAL_COMMITTEE_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COM_SUBGROUP_MAST_CUST_ID", DbType="VarChar(12)")]
		public string COM_SUBGROUP_MAST_CUST_ID
		{
			get
			{
				return this._COM_SUBGROUP_MAST_CUST_ID;
			}
			set
			{
				if ((this._COM_SUBGROUP_MAST_CUST_ID != value))
				{
					this.OnCOM_SUBGROUP_MAST_CUST_IDChanging(value);
					this.SendPropertyChanging();
					this._COM_SUBGROUP_MAST_CUST_ID = value;
					this.SendPropertyChanged("COM_SUBGROUP_MAST_CUST_ID");
					this.OnCOM_SUBGROUP_MAST_CUST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COM_SUBGROUP_SUB_CUST_ID", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> COM_SUBGROUP_SUB_CUST_ID
		{
			get
			{
				return this._COM_SUBGROUP_SUB_CUST_ID;
			}
			set
			{
				if ((this._COM_SUBGROUP_SUB_CUST_ID != value))
				{
					this.OnCOM_SUBGROUP_SUB_CUST_IDChanging(value);
					this.SendPropertyChanging();
					this._COM_SUBGROUP_SUB_CUST_ID = value;
					this.SendPropertyChanged("COM_SUBGROUP_SUB_CUST_ID");
					this.OnCOM_SUBGROUP_SUB_CUST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_VOLUNTEER_FLAG", DbType="Char(1)")]
		public System.Nullable<char> CUS_VOLUNTEER_FLAG
		{
			get
			{
				return this._CUS_VOLUNTEER_FLAG;
			}
			set
			{
				if ((this._CUS_VOLUNTEER_FLAG != value))
				{
					this.OnCUS_VOLUNTEER_FLAGChanging(value);
					this.SendPropertyChanging();
					this._CUS_VOLUNTEER_FLAG = value;
					this.SendPropertyChanged("CUS_VOLUNTEER_FLAG");
					this.OnCUS_VOLUNTEER_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADVERTISER_FLAG", DbType="Char(1) NOT NULL")]
		public char ADVERTISER_FLAG
		{
			get
			{
				return this._ADVERTISER_FLAG;
			}
			set
			{
				if ((this._ADVERTISER_FLAG != value))
				{
					this.OnADVERTISER_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ADVERTISER_FLAG = value;
					this.SendPropertyChanged("ADVERTISER_FLAG");
					this.OnADVERTISER_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADVERTISING_AGENCY_FLAG", DbType="Char(1) NOT NULL")]
		public char ADVERTISING_AGENCY_FLAG
		{
			get
			{
				return this._ADVERTISING_AGENCY_FLAG;
			}
			set
			{
				if ((this._ADVERTISING_AGENCY_FLAG != value))
				{
					this.OnADVERTISING_AGENCY_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ADVERTISING_AGENCY_FLAG = value;
					this.SendPropertyChanged("ADVERTISING_AGENCY_FLAG");
					this.OnADVERTISING_AGENCY_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPA_TITLE_ONLY_FLAG", DbType="Char(1) NOT NULL")]
		public char BPA_TITLE_ONLY_FLAG
		{
			get
			{
				return this._BPA_TITLE_ONLY_FLAG;
			}
			set
			{
				if ((this._BPA_TITLE_ONLY_FLAG != value))
				{
					this.OnBPA_TITLE_ONLY_FLAGChanging(value);
					this.SendPropertyChanging();
					this._BPA_TITLE_ONLY_FLAG = value;
					this.SendPropertyChanged("BPA_TITLE_ONLY_FLAG");
					this.OnBPA_TITLE_ONLY_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROSPECT_ID", DbType="VarChar(12)")]
		public string PROSPECT_ID
		{
			get
			{
				return this._PROSPECT_ID;
			}
			set
			{
				if ((this._PROSPECT_ID != value))
				{
					this.OnPROSPECT_IDChanging(value);
					this.SendPropertyChanging();
					this._PROSPECT_ID = value;
					this.SendPropertyChanged("PROSPECT_ID");
					this.OnPROSPECT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POTENTIAL_DUPLICATE_REVIEW_FLAG", DbType="Char(1) NOT NULL")]
		public char POTENTIAL_DUPLICATE_REVIEW_FLAG
		{
			get
			{
				return this._POTENTIAL_DUPLICATE_REVIEW_FLAG;
			}
			set
			{
				if ((this._POTENTIAL_DUPLICATE_REVIEW_FLAG != value))
				{
					this.OnPOTENTIAL_DUPLICATE_REVIEW_FLAGChanging(value);
					this.SendPropertyChanging();
					this._POTENTIAL_DUPLICATE_REVIEW_FLAG = value;
					this.SendPropertyChanged("POTENTIAL_DUPLICATE_REVIEW_FLAG");
					this.OnPOTENTIAL_DUPLICATE_REVIEW_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUPLICATE_REASON", DbType="VarChar(255)")]
		public string DUPLICATE_REASON
		{
			get
			{
				return this._DUPLICATE_REASON;
			}
			set
			{
				if ((this._DUPLICATE_REASON != value))
				{
					this.OnDUPLICATE_REASONChanging(value);
					this.SendPropertyChanging();
					this._DUPLICATE_REASON = value;
					this.SendPropertyChanged("DUPLICATE_REASON");
					this.OnDUPLICATE_REASONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POTENTIAL_MATCH_PROBABILITY", DbType="Decimal(6,3)")]
		public System.Nullable<decimal> POTENTIAL_MATCH_PROBABILITY
		{
			get
			{
				return this._POTENTIAL_MATCH_PROBABILITY;
			}
			set
			{
				if ((this._POTENTIAL_MATCH_PROBABILITY != value))
				{
					this.OnPOTENTIAL_MATCH_PROBABILITYChanging(value);
					this.SendPropertyChanging();
					this._POTENTIAL_MATCH_PROBABILITY = value;
					this.SendPropertyChanged("POTENTIAL_MATCH_PROBABILITY");
					this.OnPOTENTIAL_MATCH_PROBABILITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORIGINAL_ORG_ID", DbType="VarChar(8)")]
		public string ORIGINAL_ORG_ID
		{
			get
			{
				return this._ORIGINAL_ORG_ID;
			}
			set
			{
				if ((this._ORIGINAL_ORG_ID != value))
				{
					this.OnORIGINAL_ORG_IDChanging(value);
					this.SendPropertyChanging();
					this._ORIGINAL_ORG_ID = value;
					this.SendPropertyChanged("ORIGINAL_ORG_ID");
					this.OnORIGINAL_ORG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORIGINAL_ORG_UNIT_ID", DbType="VarChar(8)")]
		public string ORIGINAL_ORG_UNIT_ID
		{
			get
			{
				return this._ORIGINAL_ORG_UNIT_ID;
			}
			set
			{
				if ((this._ORIGINAL_ORG_UNIT_ID != value))
				{
					this.OnORIGINAL_ORG_UNIT_IDChanging(value);
					this.SendPropertyChanging();
					this._ORIGINAL_ORG_UNIT_ID = value;
					this.SendPropertyChanged("ORIGINAL_ORG_UNIT_ID");
					this.OnORIGINAL_ORG_UNIT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORIGINAL_SOURCE_CODE", DbType="VarChar(24)")]
		public string ORIGINAL_SOURCE_CODE
		{
			get
			{
				return this._ORIGINAL_SOURCE_CODE;
			}
			set
			{
				if ((this._ORIGINAL_SOURCE_CODE != value))
				{
					this.OnORIGINAL_SOURCE_CODEChanging(value);
					this.SendPropertyChanging();
					this._ORIGINAL_SOURCE_CODE = value;
					this.SendPropertyChanged("ORIGINAL_SOURCE_CODE");
					this.OnORIGINAL_SOURCE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALLOW_SYSTEM_NOTIFICATION_FLAG", DbType="Char(1) NOT NULL")]
		public char ALLOW_SYSTEM_NOTIFICATION_FLAG
		{
			get
			{
				return this._ALLOW_SYSTEM_NOTIFICATION_FLAG;
			}
			set
			{
				if ((this._ALLOW_SYSTEM_NOTIFICATION_FLAG != value))
				{
					this.OnALLOW_SYSTEM_NOTIFICATION_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ALLOW_SYSTEM_NOTIFICATION_FLAG = value;
					this.SendPropertyChanged("ALLOW_SYSTEM_NOTIFICATION_FLAG");
					this.OnALLOW_SYSTEM_NOTIFICATION_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPOUSE_FIRST_NAME", DbType="VarChar(40)")]
		public string SPOUSE_FIRST_NAME
		{
			get
			{
				return this._SPOUSE_FIRST_NAME;
			}
			set
			{
				if ((this._SPOUSE_FIRST_NAME != value))
				{
					this.OnSPOUSE_FIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SPOUSE_FIRST_NAME = value;
					this.SendPropertyChanged("SPOUSE_FIRST_NAME");
					this.OnSPOUSE_FIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARITAL_STATUS_CODE", DbType="VarChar(24)")]
		public string MARITAL_STATUS_CODE
		{
			get
			{
				return this._MARITAL_STATUS_CODE;
			}
			set
			{
				if ((this._MARITAL_STATUS_CODE != value))
				{
					this.OnMARITAL_STATUS_CODEChanging(value);
					this.SendPropertyChanging();
					this._MARITAL_STATUS_CODE = value;
					this.SendPropertyChanged("MARITAL_STATUS_CODE");
					this.OnMARITAL_STATUS_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALLOW_ADVOCACY_FLAG", DbType="Char(1)")]
		public System.Nullable<char> ALLOW_ADVOCACY_FLAG
		{
			get
			{
				return this._ALLOW_ADVOCACY_FLAG;
			}
			set
			{
				if ((this._ALLOW_ADVOCACY_FLAG != value))
				{
					this.OnALLOW_ADVOCACY_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ALLOW_ADVOCACY_FLAG = value;
					this.SendPropertyChanged("ALLOW_ADVOCACY_FLAG");
					this.OnALLOW_ADVOCACY_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENCY_CODE", DbType="VarChar(24)")]
		public string CURRENCY_CODE
		{
			get
			{
				return this._CURRENCY_CODE;
			}
			set
			{
				if ((this._CURRENCY_CODE != value))
				{
					this.OnCURRENCY_CODEChanging(value);
					this.SendPropertyChanging();
					this._CURRENCY_CODE = value;
					this.SendPropertyChanged("CURRENCY_CODE");
					this.OnCURRENCY_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_SEARCH_GROUP", DbType="VarChar(12)")]
		public string PRIMARY_SEARCH_GROUP
		{
			get
			{
				return this._PRIMARY_SEARCH_GROUP;
			}
			set
			{
				if ((this._PRIMARY_SEARCH_GROUP != value))
				{
					this.OnPRIMARY_SEARCH_GROUPChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_SEARCH_GROUP = value;
					this.SendPropertyChanged("PRIMARY_SEARCH_GROUP");
					this.OnPRIMARY_SEARCH_GROUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_CANDIDATE_ID_OVERRIDE", DbType="VarChar(12)")]
		public string USR_CANDIDATE_ID_OVERRIDE
		{
			get
			{
				return this._USR_CANDIDATE_ID_OVERRIDE;
			}
			set
			{
				if ((this._USR_CANDIDATE_ID_OVERRIDE != value))
				{
					this.OnUSR_CANDIDATE_ID_OVERRIDEChanging(value);
					this.SendPropertyChanging();
					this._USR_CANDIDATE_ID_OVERRIDE = value;
					this.SendPropertyChanged("USR_CANDIDATE_ID_OVERRIDE");
					this.OnUSR_CANDIDATE_ID_OVERRIDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_ALLOW_MARKETING_EMAIL", DbType="Char(1)")]
		public System.Nullable<char> USR_ALLOW_MARKETING_EMAIL
		{
			get
			{
				return this._USR_ALLOW_MARKETING_EMAIL;
			}
			set
			{
				if ((this._USR_ALLOW_MARKETING_EMAIL != value))
				{
					this.OnUSR_ALLOW_MARKETING_EMAILChanging(value);
					this.SendPropertyChanging();
					this._USR_ALLOW_MARKETING_EMAIL = value;
					this.SendPropertyChanged("USR_ALLOW_MARKETING_EMAIL");
					this.OnUSR_ALLOW_MARKETING_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_HEAP_MASTER", DbType="Char(1)")]
		public System.Nullable<char> USR_HEAP_MASTER
		{
			get
			{
				return this._USR_HEAP_MASTER;
			}
			set
			{
				if ((this._USR_HEAP_MASTER != value))
				{
					this.OnUSR_HEAP_MASTERChanging(value);
					this.SendPropertyChanging();
					this._USR_HEAP_MASTER = value;
					this.SendPropertyChanged("USR_HEAP_MASTER");
					this.OnUSR_HEAP_MASTERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_GRADUATION_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> USR_GRADUATION_DATE
		{
			get
			{
				return this._USR_GRADUATION_DATE;
			}
			set
			{
				if ((this._USR_GRADUATION_DATE != value))
				{
					this.OnUSR_GRADUATION_DATEChanging(value);
					this.SendPropertyChanging();
					this._USR_GRADUATION_DATE = value;
					this.SendPropertyChanged("USR_GRADUATION_DATE");
					this.OnUSR_GRADUATION_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_FACEBOOK_UID", DbType="VarChar(50)")]
		public string USR_FACEBOOK_UID
		{
			get
			{
				return this._USR_FACEBOOK_UID;
			}
			set
			{
				if ((this._USR_FACEBOOK_UID != value))
				{
					this.OnUSR_FACEBOOK_UIDChanging(value);
					this.SendPropertyChanging();
					this._USR_FACEBOOK_UID = value;
					this.SendPropertyChanged("USR_FACEBOOK_UID");
					this.OnUSR_FACEBOOK_UIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_AVATAR", DbType="VarChar(1000)")]
		public string USR_AVATAR
		{
			get
			{
				return this._USR_AVATAR;
			}
			set
			{
				if ((this._USR_AVATAR != value))
				{
					this.OnUSR_AVATARChanging(value);
					this.SendPropertyChanging();
					this._USR_AVATAR = value;
					this.SendPropertyChanged("USR_AVATAR");
					this.OnUSR_AVATARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_FORUM_MEMBER", DbType="Char(1)")]
		public System.Nullable<char> USR_FORUM_MEMBER
		{
			get
			{
				return this._USR_FORUM_MEMBER;
			}
			set
			{
				if ((this._USR_FORUM_MEMBER != value))
				{
					this.OnUSR_FORUM_MEMBERChanging(value);
					this.SendPropertyChanging();
					this._USR_FORUM_MEMBER = value;
					this.SendPropertyChanged("USR_FORUM_MEMBER");
					this.OnUSR_FORUM_MEMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_CUSTOMER_INFO_INCOMPLETE", DbType="Char(1)")]
		public System.Nullable<char> USR_CUSTOMER_INFO_INCOMPLETE
		{
			get
			{
				return this._USR_CUSTOMER_INFO_INCOMPLETE;
			}
			set
			{
				if ((this._USR_CUSTOMER_INFO_INCOMPLETE != value))
				{
					this.OnUSR_CUSTOMER_INFO_INCOMPLETEChanging(value);
					this.SendPropertyChanging();
					this._USR_CUSTOMER_INFO_INCOMPLETE = value;
					this.SendPropertyChanged("USR_CUSTOMER_INFO_INCOMPLETE");
					this.OnUSR_CUSTOMER_INFO_INCOMPLETEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_FREE_MEMBERSHIP_UPGRADE", DbType="Char(1)")]
		public System.Nullable<char> USR_FREE_MEMBERSHIP_UPGRADE
		{
			get
			{
				return this._USR_FREE_MEMBERSHIP_UPGRADE;
			}
			set
			{
				if ((this._USR_FREE_MEMBERSHIP_UPGRADE != value))
				{
					this.OnUSR_FREE_MEMBERSHIP_UPGRADEChanging(value);
					this.SendPropertyChanging();
					this._USR_FREE_MEMBERSHIP_UPGRADE = value;
					this.SendPropertyChanged("USR_FREE_MEMBERSHIP_UPGRADE");
					this.OnUSR_FREE_MEMBERSHIP_UPGRADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAMILY_FLAG", DbType="Char(1) NOT NULL")]
		public char FAMILY_FLAG
		{
			get
			{
				return this._FAMILY_FLAG;
			}
			set
			{
				if ((this._FAMILY_FLAG != value))
				{
					this.OnFAMILY_FLAGChanging(value);
					this.SendPropertyChanging();
					this._FAMILY_FLAG = value;
					this.SendPropertyChanged("FAMILY_FLAG");
					this.OnFAMILY_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_SEARCH_GROUP_OVERRIDE_FLAG", DbType="Char(1)")]
		public System.Nullable<char> PRIMARY_SEARCH_GROUP_OVERRIDE_FLAG
		{
			get
			{
				return this._PRIMARY_SEARCH_GROUP_OVERRIDE_FLAG;
			}
			set
			{
				if ((this._PRIMARY_SEARCH_GROUP_OVERRIDE_FLAG != value))
				{
					this.OnPRIMARY_SEARCH_GROUP_OVERRIDE_FLAGChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_SEARCH_GROUP_OVERRIDE_FLAG = value;
					this.SendPropertyChanged("PRIMARY_SEARCH_GROUP_OVERRIDE_FLAG");
					this.OnPRIMARY_SEARCH_GROUP_OVERRIDE_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_CREDENTIALS_DESC", DbType="VarChar(40)")]
		public string NAME_CREDENTIALS_DESC
		{
			get
			{
				return this._NAME_CREDENTIALS_DESC;
			}
			set
			{
				if ((this._NAME_CREDENTIALS_DESC != value))
				{
					this.OnNAME_CREDENTIALS_DESCChanging(value);
					this.SendPropertyChanging();
					this._NAME_CREDENTIALS_DESC = value;
					this.SendPropertyChanged("NAME_CREDENTIALS_DESC");
					this.OnNAME_CREDENTIALS_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_FAMILY_CONTACT_MAST_CUST_ID", DbType="VarChar(12)")]
		public string PRIMARY_FAMILY_CONTACT_MAST_CUST_ID
		{
			get
			{
				return this._PRIMARY_FAMILY_CONTACT_MAST_CUST_ID;
			}
			set
			{
				if ((this._PRIMARY_FAMILY_CONTACT_MAST_CUST_ID != value))
				{
					this.OnPRIMARY_FAMILY_CONTACT_MAST_CUST_IDChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_FAMILY_CONTACT_MAST_CUST_ID = value;
					this.SendPropertyChanged("PRIMARY_FAMILY_CONTACT_MAST_CUST_ID");
					this.OnPRIMARY_FAMILY_CONTACT_MAST_CUST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_FAMILY_CONTACT_SUB_CUST_ID", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> PRIMARY_FAMILY_CONTACT_SUB_CUST_ID
		{
			get
			{
				return this._PRIMARY_FAMILY_CONTACT_SUB_CUST_ID;
			}
			set
			{
				if ((this._PRIMARY_FAMILY_CONTACT_SUB_CUST_ID != value))
				{
					this.OnPRIMARY_FAMILY_CONTACT_SUB_CUST_IDChanging(value);
					this.SendPropertyChanging();
					this._PRIMARY_FAMILY_CONTACT_SUB_CUST_ID = value;
					this.SendPropertyChanged("PRIMARY_FAMILY_CONTACT_SUB_CUST_ID");
					this.OnPRIMARY_FAMILY_CONTACT_SUB_CUST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INCLUDE_IN_WEB_MOBILE_DIRECTORY_FLAG", DbType="Char(1) NOT NULL")]
		public char INCLUDE_IN_WEB_MOBILE_DIRECTORY_FLAG
		{
			get
			{
				return this._INCLUDE_IN_WEB_MOBILE_DIRECTORY_FLAG;
			}
			set
			{
				if ((this._INCLUDE_IN_WEB_MOBILE_DIRECTORY_FLAG != value))
				{
					this.OnINCLUDE_IN_WEB_MOBILE_DIRECTORY_FLAGChanging(value);
					this.SendPropertyChanging();
					this._INCLUDE_IN_WEB_MOBILE_DIRECTORY_FLAG = value;
					this.SendPropertyChanged("INCLUDE_IN_WEB_MOBILE_DIRECTORY_FLAG");
					this.OnINCLUDE_IN_WEB_MOBILE_DIRECTORY_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_CHECKOUT_FLAG", DbType="Char(1) NOT NULL")]
		public char GUEST_CHECKOUT_FLAG
		{
			get
			{
				return this._GUEST_CHECKOUT_FLAG;
			}
			set
			{
				if ((this._GUEST_CHECKOUT_FLAG != value))
				{
					this.OnGUEST_CHECKOUT_FLAGChanging(value);
					this.SendPropertyChanging();
					this._GUEST_CHECKOUT_FLAG = value;
					this.SendPropertyChanged("GUEST_CHECKOUT_FLAG");
					this.OnGUEST_CHECKOUT_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_TRAINING_BUDGET_SIZE_CODE", DbType="VarChar(24)")]
		public string USR_TRAINING_BUDGET_SIZE_CODE
		{
			get
			{
				return this._USR_TRAINING_BUDGET_SIZE_CODE;
			}
			set
			{
				if ((this._USR_TRAINING_BUDGET_SIZE_CODE != value))
				{
					this.OnUSR_TRAINING_BUDGET_SIZE_CODEChanging(value);
					this.SendPropertyChanging();
					this._USR_TRAINING_BUDGET_SIZE_CODE = value;
					this.SendPropertyChanged("USR_TRAINING_BUDGET_SIZE_CODE");
					this.OnUSR_TRAINING_BUDGET_SIZE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_DIRECT_REPORT_COUNT_CODE", DbType="VarChar(24)")]
		public string USR_DIRECT_REPORT_COUNT_CODE
		{
			get
			{
				return this._USR_DIRECT_REPORT_COUNT_CODE;
			}
			set
			{
				if ((this._USR_DIRECT_REPORT_COUNT_CODE != value))
				{
					this.OnUSR_DIRECT_REPORT_COUNT_CODEChanging(value);
					this.SendPropertyChanging();
					this._USR_DIRECT_REPORT_COUNT_CODE = value;
					this.SendPropertyChanged("USR_DIRECT_REPORT_COUNT_CODE");
					this.OnUSR_DIRECT_REPORT_COUNT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_SSO_USERNAME", DbType="VarChar(50)")]
		public string USR_SSO_USERNAME
		{
			get
			{
				return this._USR_SSO_USERNAME;
			}
			set
			{
				if ((this._USR_SSO_USERNAME != value))
				{
					this.OnUSR_SSO_USERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USR_SSO_USERNAME = value;
					this.SendPropertyChanged("USR_SSO_USERNAME");
					this.OnUSR_SSO_USERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_JOB_BANK_CODE", DbType="VarChar(50)")]
		public string USR_JOB_BANK_CODE
		{
			get
			{
				return this._USR_JOB_BANK_CODE;
			}
			set
			{
				if ((this._USR_JOB_BANK_CODE != value))
				{
					this.OnUSR_JOB_BANK_CODEChanging(value);
					this.SendPropertyChanging();
					this._USR_JOB_BANK_CODE = value;
					this.SendPropertyChanged("USR_JOB_BANK_CODE");
					this.OnUSR_JOB_BANK_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_FORUM_MEMBER_SINCE", DbType="VarChar(50)")]
		public string USR_FORUM_MEMBER_SINCE
		{
			get
			{
				return this._USR_FORUM_MEMBER_SINCE;
			}
			set
			{
				if ((this._USR_FORUM_MEMBER_SINCE != value))
				{
					this.OnUSR_FORUM_MEMBER_SINCEChanging(value);
					this.SendPropertyChanging();
					this._USR_FORUM_MEMBER_SINCE = value;
					this.SendPropertyChanged("USR_FORUM_MEMBER_SINCE");
					this.OnUSR_FORUM_MEMBER_SINCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_FORUM_PARTNER_CODE", DbType="VarChar(50)")]
		public string USR_FORUM_PARTNER_CODE
		{
			get
			{
				return this._USR_FORUM_PARTNER_CODE;
			}
			set
			{
				if ((this._USR_FORUM_PARTNER_CODE != value))
				{
					this.OnUSR_FORUM_PARTNER_CODEChanging(value);
					this.SendPropertyChanging();
					this._USR_FORUM_PARTNER_CODE = value;
					this.SendPropertyChanged("USR_FORUM_PARTNER_CODE");
					this.OnUSR_FORUM_PARTNER_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USR_SELECTED_TERMSCONDITIONS", DbType="DateTime")]
		public System.Nullable<System.DateTime> USR_SELECTED_TERMSCONDITIONS
		{
			get
			{
				return this._USR_SELECTED_TERMSCONDITIONS;
			}
			set
			{
				if ((this._USR_SELECTED_TERMSCONDITIONS != value))
				{
					this.OnUSR_SELECTED_TERMSCONDITIONSChanging(value);
					this.SendPropertyChanging();
					this._USR_SELECTED_TERMSCONDITIONS = value;
					this.SendPropertyChanged("USR_SELECTED_TERMSCONDITIONS");
					this.OnUSR_SELECTED_TERMSCONDITIONSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
